import type { LucideIcon } from "lucide-react";
import { BookMarked, Brain, Church, ClipboardCheck, FileText, Flame, GraduationCap, Languages, Mic2, PenLine, Route, ScrollText, SearchCheck, ShieldCheck, Sparkles, Target } from "lucide-react";

export type EvaStudioTrack = "grammar" | "religious" | "lexical";

export type EvaSkillModule = {
  id: string;
  track: EvaStudioTrack;
  order: number;
  title: string;
  focus: string;
  outcome: string;
  sourceTypes: string[];
  practice: string[];
  evidence: string;
  level: "Core" | "Deepening" | "Mastery";
  minutes: number;
  icon: LucideIcon;
};

export type EvaLexicalItem = {
  id: string;
  term: string;
  ipa: string;
  stress: string;
  meaning: string;
  ministryUse: string;
  collocations: string[];
  pronunciationTip: string;
  example: string;
  tags: string[];
};

export type EvaQuizQuestion = {
  id: string;
  track: EvaStudioTrack;
  prompt: string;
  options: string[];
  answerIndex: number;
  explanation: string;
};

export type EvaWorkflowStep = {
  id: string;
  title: string;
  text: string;
  icon: LucideIcon;
};

export const evaWorkflowSteps: EvaWorkflowStep[] = [
  {
    id: "map",
    title: "Map the page",
    text: "Start from stack, lane, chapter, or search. Every imported page remains reachable.",
    icon: Route,
  },
  {
    id: "read",
    title: "Read with purpose",
    text: "Use the active source page, then connect it to grammar, religious context, or lexical work.",
    icon: BookMarked,
  },
  {
    id: "produce",
    title: "Produce evidence",
    text: "Write a note, translation, sentence, quiz answer, or review item that can be tracked.",
    icon: PenLine,
  },
  {
    id: "review",
    title: "Review deliberately",
    text: "Complete the page, add weak items to review, and revisit pronunciation and quiz errors.",
    icon: ClipboardCheck,
  },
];

export const evaGrammarModules: EvaSkillModule[] = [
  {
    id: "grammar-tense-control",
    track: "grammar",
    order: 1,
    title: "Tense Control for Testimony",
    focus: "present perfect, past simple, time markers",
    outcome: "Tell a faith story with clean time logic and no tense drift.",
    sourceTypes: ["grammar-lesson", "grammar-practice", "chapter-language"],
    practice: ["Rewrite one testimony in two timelines.", "Mark every time phrase.", "Produce three accurate follow-up questions."],
    evidence: "A 90-word testimony paragraph with tense corrections.",
    level: "Core",
    minutes: 28,
    icon: FileText,
  },
  {
    id: "grammar-articles-specificity",
    track: "grammar",
    order: 2,
    title: "Articles & Specificity",
    focus: "a, an, the, zero article",
    outcome: "Make church and Bible explanations sound precise instead of translated.",
    sourceTypes: ["grammar-practice", "grammar-bible"],
    practice: ["Sort nouns into general/specific/unique.", "Correct five article errors.", "Explain one rule in your own words."],
    evidence: "A corrected noun map for one active page.",
    level: "Core",
    minutes: 24,
    icon: SearchCheck,
  },
  {
    id: "grammar-preposition-place",
    track: "grammar",
    order: 3,
    title: "Prepositions of Place, Purpose, and Care",
    focus: "in, at, on, for, to, with, through",
    outcome: "Use natural prepositions in prayer, service, and discussion contexts.",
    sourceTypes: ["grammar-lesson", "scenario"],
    practice: ["Underline preposition patterns.", "Build three service sentences.", "Turn one wrong sentence into a pattern card."],
    evidence: "Five corrected ministry sentences.",
    level: "Core",
    minutes: 25,
    icon: Target,
  },
  {
    id: "grammar-connectors",
    track: "grammar",
    order: 4,
    title: "Connectors for Meaning",
    focus: "because, although, therefore, however, so that",
    outcome: "Move from short answers to connected reasoning for IELTS/TOEFL-style writing.",
    sourceTypes: ["reading-lab-rc", "chapter-quiz", "progress"],
    practice: ["Combine sentence pairs.", "Label cause, contrast, result, purpose.", "Write one balanced paragraph."],
    evidence: "A five-sentence paragraph with connector labels.",
    level: "Core",
    minutes: 30,
    icon: Brain,
  },
  {
    id: "grammar-question-formation",
    track: "grammar",
    order: 5,
    title: "Question Formation for Care",
    focus: "auxiliaries, wh-questions, indirect questions",
    outcome: "Ask warm, accurate questions without sounding abrupt.",
    sourceTypes: ["listening-speaking", "scenario"],
    practice: ["Convert statements to questions.", "Soften two direct questions.", "Prepare a three-question care sequence."],
    evidence: "A short interview script for one scenario page.",
    level: "Deepening",
    minutes: 32,
    icon: Mic2,
  },
  {
    id: "grammar-modals",
    track: "grammar",
    order: 6,
    title: "Modals of Advice and Possibility",
    focus: "should, could, might, must, have to",
    outcome: "Give careful advice without overclaiming or sounding harsh.",
    sourceTypes: ["scenario", "exegesis", "translation"],
    practice: ["Rank modal strength.", "Rewrite harsh advice softly.", "Produce two pastoral response options."],
    evidence: "A modal-strength ladder with examples.",
    level: "Deepening",
    minutes: 27,
    icon: ShieldCheck,
  },
  {
    id: "grammar-relative-clauses",
    track: "grammar",
    order: 7,
    title: "Relative Clauses for Definition",
    focus: "who, which, that, where",
    outcome: "Define theological and service vocabulary with clear English.",
    sourceTypes: ["vocabulary", "translation", "chapter-reading"],
    practice: ["Define ten words with relative clauses.", "Remove repeated nouns.", "Check punctuation in long definitions."],
    evidence: "Ten clean definition cards.",
    level: "Deepening",
    minutes: 26,
    icon: Languages,
  },
  {
    id: "grammar-passive-voice",
    track: "grammar",
    order: 8,
    title: "Passive Voice and Focus",
    focus: "be + past participle, agent control",
    outcome: "Choose active or passive voice based on meaning, humility, and emphasis.",
    sourceTypes: ["grammar-bible", "exegesis", "translation"],
    practice: ["Identify actor and receiver.", "Rewrite one active paragraph as passive.", "Choose the better focus."],
    evidence: "A two-column active/passive comparison.",
    level: "Deepening",
    minutes: 34,
    icon: ScrollText,
  },
  {
    id: "grammar-conditionals",
    track: "grammar",
    order: 9,
    title: "Conditionals for Reflection",
    focus: "zero, first, second conditionals",
    outcome: "Write reflective and practical responses without grammar confusion.",
    sourceTypes: ["progress", "chapter-quiz", "journal"],
    practice: ["Sort conditional types.", "Write three real-life applications.", "Turn one reflection into an action plan."],
    evidence: "A conditional reflection ladder.",
    level: "Mastery",
    minutes: 35,
    icon: Sparkles,
  },
  {
    id: "grammar-paragraph-control",
    track: "grammar",
    order: 10,
    title: "Paragraph Control for IELTS/TOEFL",
    focus: "topic sentence, support, cohesion, closing",
    outcome: "Convert workbook answers into exam-quality writing evidence.",
    sourceTypes: ["reading-lab", "reading-lab-rc", "progress"],
    practice: ["Choose a topic sentence.", "Add one example and one explanation.", "Revise for cohesion and grammar control."],
    evidence: "One polished 140-word paragraph.",
    level: "Mastery",
    minutes: 40,
    icon: GraduationCap,
  },
];

export const evaReligiousModules: EvaSkillModule[] = [
  {
    id: "religious-calling",
    track: "religious",
    order: 1,
    title: "Calling and Vocation",
    focus: "purpose, service, gifts, discipline",
    outcome: "Explain calling in careful English without vague spiritual wording.",
    sourceTypes: ["lesson", "progress", "chapter-reading"],
    practice: ["Write a calling statement.", "Name one gift and one discipline.", "Connect purpose to one habit."],
    evidence: "A two-sentence calling note.",
    level: "Core",
    minutes: 24,
    icon: Flame,
  },
  {
    id: "religious-prayer",
    track: "religious",
    order: 2,
    title: "Prayer Language",
    focus: "gratitude, request, confession, intercession",
    outcome: "Build prayer sentences that sound sincere, simple, and accurate.",
    sourceTypes: ["lesson", "listening-speaking", "grammar-bible"],
    practice: ["Classify prayer lines.", "Rewrite one line more naturally.", "Record a 30-second prayer rehearsal."],
    evidence: "Four prayer-line sentence patterns.",
    level: "Core",
    minutes: 26,
    icon: Church,
  },
  {
    id: "religious-worship",
    track: "religious",
    order: 3,
    title: "Worship and Reverence",
    focus: "praise, reverence, community language",
    outcome: "Describe worship without overusing generic adjectives.",
    sourceTypes: ["vocabulary", "translation", "chapter-language"],
    practice: ["Collect five worship collocations.", "Write one definition.", "Translate one idea back into natural English."],
    evidence: "A worship vocabulary mini-bank.",
    level: "Core",
    minutes: 25,
    icon: Sparkles,
  },
  {
    id: "religious-scripture-reading",
    track: "religious",
    order: 4,
    title: "Scripture Reading Method",
    focus: "observe, interpret, apply, respond",
    outcome: "Read a passage like a learner, not only like a translator.",
    sourceTypes: ["exegesis", "chapter-reading", "reading-lab"],
    practice: ["Write one observation.", "Separate interpretation from application.", "Create one response sentence."],
    evidence: "An O-I-A-R reading note.",
    level: "Deepening",
    minutes: 35,
    icon: BookMarked,
  },
  {
    id: "religious-parables",
    track: "religious",
    order: 5,
    title: "Parables and Moral Contrast",
    focus: "story, contrast, lesson, application",
    outcome: "Summarize spiritual stories with clear plot and moral movement.",
    sourceTypes: ["reading-lab", "exegesis", "translation"],
    practice: ["Identify conflict and lesson.", "Write a neutral summary.", "Write one personal application."],
    evidence: "A story-to-application bridge.",
    level: "Deepening",
    minutes: 34,
    icon: ScrollText,
  },
  {
    id: "religious-compassion",
    track: "religious",
    order: 6,
    title: "Compassion and Care",
    focus: "listening, presence, gentle response",
    outcome: "Use English that protects dignity in care situations.",
    sourceTypes: ["scenario", "listening-speaking", "gallery"],
    practice: ["Choose a gentle opener.", "Avoid fixing too quickly.", "Prepare one follow-up question."],
    evidence: "A three-turn care dialogue.",
    level: "Deepening",
    minutes: 30,
    icon: ShieldCheck,
  },
  {
    id: "religious-testimony",
    track: "religious",
    order: 7,
    title: "Testimony Structure",
    focus: "before, turning point, change, present practice",
    outcome: "Share a testimony with structure, humility, and grammar control.",
    sourceTypes: ["grammar-lesson", "progress", "listening-speaking"],
    practice: ["Outline four stages.", "Cut unclear details.", "Add one concrete present habit."],
    evidence: "A 60-second testimony outline.",
    level: "Deepening",
    minutes: 38,
    icon: Mic2,
  },
  {
    id: "religious-church-community",
    track: "religious",
    order: 8,
    title: "Church Community Language",
    focus: "roles, gatherings, belonging, service teams",
    outcome: "Talk about church life with accurate and respectful vocabulary.",
    sourceTypes: ["vocabulary", "scenario", "translation"],
    practice: ["Define five church roles.", "Write one welcome line.", "Translate one announcement naturally."],
    evidence: "A church community word map.",
    level: "Core",
    minutes: 28,
    icon: Church,
  },
  {
    id: "religious-translation-ethics",
    track: "religious",
    order: 9,
    title: "Faithful Translation Ethics",
    focus: "accuracy, tone, context, humility",
    outcome: "Make translation choices that preserve meaning without flattening tone.",
    sourceTypes: ["translation", "exegesis"],
    practice: ["List meaning risks.", "Choose a translation strategy.", "Write one revision note."],
    evidence: "A translation decision memo.",
    level: "Mastery",
    minutes: 40,
    icon: Languages,
  },
  {
    id: "religious-wisdom-discernment",
    track: "religious",
    order: 10,
    title: "Wisdom and Discernment",
    focus: "decision language, counsel, reflection",
    outcome: "Discuss decisions with balanced English and mature reasoning.",
    sourceTypes: ["progress", "chapter-quiz", "exegesis"],
    practice: ["Separate fact, feeling, counsel, and decision.", "Write one wise next step.", "Quiz yourself on tone."],
    evidence: "A four-part discernment note.",
    level: "Mastery",
    minutes: 36,
    icon: Brain,
  },
];

export const evaLexicalResource: EvaLexicalItem[] = [
  {
    id: "lex-calling",
    term: "calling",
    ipa: "/ˈkɔː.lɪŋ/",
    stress: "CALL-ing",
    meaning: "a strong sense of purpose or vocation",
    ministryUse: "Use it for purpose, not just a job title.",
    collocations: ["sense of calling", "follow a calling", "clarify a calling"],
    pronunciationTip: "Keep the first syllable long and clear; do not add an extra vowel after /l/.",
    example: "She is learning English to clarify her calling and serve with more confidence.",
    tags: ["purpose", "testimony", "vocation"],
  },
  {
    id: "lex-discernment",
    term: "discernment",
    ipa: "/dɪˈsɜːrn.mənt/",
    stress: "di-SERN-ment",
    meaning: "the ability to judge wisely and notice what matters",
    ministryUse: "Useful for decisions, counsel, and reflection.",
    collocations: ["spiritual discernment", "practice discernment", "discernment process"],
    pronunciationTip: "The stress is on the second syllable; the final syllable is soft.",
    example: "Good discernment needs prayer, evidence, and honest reflection.",
    tags: ["wisdom", "decision", "reflection"],
  },
  {
    id: "lex-reverence",
    term: "reverence",
    ipa: "/ˈrev.ər.əns/",
    stress: "REV-er-ence",
    meaning: "deep respect expressed through attitude or action",
    ministryUse: "A precise word for worship, tone, and sacred attention.",
    collocations: ["show reverence", "deep reverence", "reverent tone"],
    pronunciationTip: "Do not pronounce it like three heavy syllables; keep the middle light.",
    example: "Her translation kept the reverence of the original prayer.",
    tags: ["worship", "tone", "translation"],
  },
  {
    id: "lex-intercession",
    term: "intercession",
    ipa: "/ˌɪn.tərˈseʃ.ən/",
    stress: "in-ter-SESH-en",
    meaning: "prayer or action on behalf of another person",
    ministryUse: "Useful when describing prayer for others.",
    collocations: ["intercession for", "prayer of intercession", "intercessory prayer"],
    pronunciationTip: "Stress the 'sesh' sound; keep the ending short.",
    example: "The group spent ten minutes in intercession for the sick.",
    tags: ["prayer", "care", "community"],
  },
  {
    id: "lex-exegesis",
    term: "exegesis",
    ipa: "/ˌek.səˈdʒiː.sɪs/",
    stress: "ek-suh-JEE-sis",
    meaning: "careful explanation of a text based on context",
    ministryUse: "Use it when studying meaning, not just giving opinion.",
    collocations: ["biblical exegesis", "careful exegesis", "exegesis note"],
    pronunciationTip: "The main stress is on 'JEE'; avoid saying 'exercise'.",
    example: "Her exegesis note separated observation from application.",
    tags: ["reading", "interpretation", "Bible"],
  },
  {
    id: "lex-testimony",
    term: "testimony",
    ipa: "/ˈtes.tə.moʊ.ni/",
    stress: "TES-ti-mo-ny",
    meaning: "a spoken or written account of personal experience or faith",
    ministryUse: "Use it for structured personal witness, not random life story.",
    collocations: ["share a testimony", "personal testimony", "testimony structure"],
    pronunciationTip: "The first syllable is strongest; keep the final sound light.",
    example: "A clear testimony has a before, a turning point, and a present practice.",
    tags: ["speaking", "story", "faith"],
  },
  {
    id: "lex-fellowship",
    term: "fellowship",
    ipa: "/ˈfel.oʊ.ʃɪp/",
    stress: "FEL-low-ship",
    meaning: "supportive spiritual community and shared life",
    ministryUse: "More than friendship; it often means shared faith and care.",
    collocations: ["church fellowship", "time of fellowship", "fellowship group"],
    pronunciationTip: "Keep the /ʃ/ sound in 'ship' clear.",
    example: "The class practiced welcome lines for a fellowship gathering.",
    tags: ["church", "community", "care"],
  },
  {
    id: "lex-compassion",
    term: "compassion",
    ipa: "/kəmˈpæʃ.ən/",
    stress: "kum-PASH-en",
    meaning: "care that notices suffering and moves toward help",
    ministryUse: "A stronger word than kindness when suffering is involved.",
    collocations: ["show compassion", "compassionate response", "deep compassion"],
    pronunciationTip: "Stress 'pash'; avoid a flat first syllable.",
    example: "A compassionate response listens before giving advice.",
    tags: ["care", "scenario", "tone"],
  },
  {
    id: "lex-stewardship",
    term: "stewardship",
    ipa: "/ˈstuː.ərd.ʃɪp/",
    stress: "STEW-ard-ship",
    meaning: "responsible care for something entrusted to you",
    ministryUse: "Useful for time, gifts, money, learning, and service.",
    collocations: ["good stewardship", "stewardship of time", "practice stewardship"],
    pronunciationTip: "The first syllable is like 'stew'; keep 'ard' light.",
    example: "Weekly review is stewardship of the learning process.",
    tags: ["growth", "discipline", "service"],
  },
  {
    id: "lex-cohesion",
    term: "cohesion",
    ipa: "/koʊˈhiː.ʒən/",
    stress: "ko-HEE-zhun",
    meaning: "the way sentences connect smoothly",
    ministryUse: "Important for IELTS/TOEFL writing and clear teaching notes.",
    collocations: ["text cohesion", "improve cohesion", "cohesive paragraph"],
    pronunciationTip: "The middle sound is long /hiː/; the final consonant is soft.",
    example: "Connectors improved the cohesion of her paragraph.",
    tags: ["writing", "grammar", "IELTS/TOEFL"],
  },
];

const grammarQuizQuestions: EvaQuizQuestion[] = [
  {
    id: "quiz-grammar-tense",
    track: "grammar",
    prompt: "Which sentence has the clearest tense control?",
    options: [
      "I learned English since two years.",
      "I have studied English for two years.",
      "I study English since two years ago.",
      "I am studying English from two years.",
    ],
    answerIndex: 1,
    explanation: "Present perfect with 'for two years' shows an action continuing until now.",
  },
  {
    id: "quiz-grammar-past-vs-present-perfect",
    track: "grammar",
    prompt: "Which sentence best separates a finished event from present evidence?",
    options: [
      "I have visited the class yesterday and I learned a lot.",
      "I visited the class yesterday, and I have written my reflection.",
      "I visit the class yesterday, and I write my reflection.",
      "I have visited yesterday, and I have wrote my reflection.",
    ],
    answerIndex: 1,
    explanation: "Past simple fits a finished time marker like 'yesterday'; present perfect fits evidence that exists now.",
  },
  {
    id: "quiz-grammar-article-specific",
    track: "grammar",
    prompt: "Choose the most natural article pattern.",
    options: [
      "Eva wrote the answer about a passage she read today.",
      "Eva wrote answer about passage she read today.",
      "Eva wrote an answer about the passage she read today.",
      "Eva wrote a answer about a passage she read today.",
    ],
    answerIndex: 2,
    explanation: "'An answer' is singular countable, and 'the passage' is specific because it was already read.",
  },
  {
    id: "quiz-grammar-connector",
    track: "grammar",
    prompt: "Choose the connector that best shows contrast: 'The text is difficult, ___ it is worth reading carefully.'",
    options: ["because", "therefore", "although", "so that"],
    answerIndex: 2,
    explanation: "'Although' creates contrast between difficulty and value.",
  },
  {
    id: "quiz-grammar-purpose-connector",
    track: "grammar",
    prompt: "Choose the connector that shows purpose: 'She reviews the sentence ___ she can explain it clearly.'",
    options: ["although", "so that", "however", "because of"],
    answerIndex: 1,
    explanation: "'So that' introduces purpose or intended result.",
  },
  {
    id: "quiz-grammar-modal",
    track: "grammar",
    prompt: "Which modal is softest for advice?",
    options: ["must", "could", "have to", "cannot"],
    answerIndex: 1,
    explanation: "'Could' suggests an option; it is softer than obligation language.",
  },
  {
    id: "quiz-grammar-indirect-question",
    track: "grammar",
    prompt: "Which indirect question is grammatically correct?",
    options: [
      "Can you tell me where is the main idea?",
      "Can you tell me where the main idea is?",
      "Can you tell me where the main idea?",
      "Can you tell me where does the main idea is?",
    ],
    answerIndex: 1,
    explanation: "In an indirect question, word order returns to statement order: 'where the main idea is.'",
  },
  {
    id: "quiz-grammar-relative-clause",
    track: "grammar",
    prompt: "Choose the best relative clause for a definition.",
    options: [
      "A mentor is a person who guides a learner.",
      "A mentor is a person which guides a learner.",
      "A mentor is a person where guides a learner.",
      "A mentor is a person guides a learner.",
    ],
    answerIndex: 0,
    explanation: "'Who' refers to people and creates a clean definition.",
  },
  {
    id: "quiz-grammar-passive-focus",
    track: "grammar",
    prompt: "Which sentence uses passive voice correctly?",
    options: [
      "The draft was revised after the lesson.",
      "The draft revised after the lesson.",
      "The draft was revise after the lesson.",
      "The draft is revising after the lesson.",
    ],
    answerIndex: 0,
    explanation: "Passive voice uses 'be' plus past participle: 'was revised.'",
  },
  {
    id: "quiz-grammar-conditional",
    track: "grammar",
    prompt: "Which sentence is a natural first conditional?",
    options: [
      "If Eva reviews daily, she will remember more.",
      "If Eva reviewed daily, she will remembers more.",
      "If Eva reviews daily, she remembered more.",
      "If Eva will review daily, she remembers more.",
    ],
    answerIndex: 0,
    explanation: "The first conditional uses present simple in the if-clause and 'will' in the result clause.",
  },
  {
    id: "quiz-grammar-paragraph-control",
    track: "grammar",
    prompt: "What should a strong IELTS/TOEFL body paragraph usually include?",
    options: [
      "A topic sentence, support, explanation, and a clear link.",
      "Only one memorized sentence.",
      "A list of unrelated vocabulary.",
      "A conclusion without evidence.",
    ],
    answerIndex: 0,
    explanation: "Academic paragraphs need a controlling idea and developed support.",
  },
];

const religiousQuizQuestions: EvaQuizQuestion[] = [
  {
    id: "quiz-religious-exegesis",
    track: "religious",
    prompt: "In careful reading, what should come before personal application?",
    options: ["Interpretation based on context", "A final opinion", "A memorized phrase", "A random translation"],
    answerIndex: 0,
    explanation: "Application is stronger when it follows observation and contextual interpretation.",
  },
  {
    id: "quiz-religious-calling",
    track: "religious",
    prompt: "Which sentence explains calling with the most care?",
    options: [
      "Calling means any job someone likes.",
      "Calling can describe purpose, service, and faithful responsibility.",
      "Calling means never changing plans.",
      "Calling is only a grammar term.",
    ],
    answerIndex: 1,
    explanation: "The studio treats calling as purpose connected to service and responsibility.",
  },
  {
    id: "quiz-religious-prayer-language",
    track: "religious",
    prompt: "Which line is the most natural prayer request?",
    options: [
      "Please help me to speak with patience and clarity.",
      "Give me success because I want all result.",
      "I demand that every mistake disappear now.",
      "Make my English perfect immediately.",
    ],
    answerIndex: 0,
    explanation: "It is simple, humble, specific, and natural.",
  },
  {
    id: "quiz-religious-worship-tone",
    track: "religious",
    prompt: "Which word best describes respectful worship language?",
    options: ["reverent", "random", "careless", "noisy"],
    answerIndex: 0,
    explanation: "'Reverent' describes deep respect in tone and action.",
  },
  {
    id: "quiz-religious-observe-interpret-apply",
    track: "religious",
    prompt: "In an observe-interpret-apply method, what is observation?",
    options: [
      "Noticing what the text actually says.",
      "Skipping the text and giving advice.",
      "Choosing a personal opinion first.",
      "Changing the passage into another topic.",
    ],
    answerIndex: 0,
    explanation: "Observation begins with careful attention to the text itself.",
  },
  {
    id: "quiz-religious-parable-summary",
    track: "religious",
    prompt: "A useful parable summary should include...",
    options: [
      "only the final sentence",
      "the situation, contrast, lesson, and application",
      "unrelated grammar rules",
      "a payment instruction",
    ],
    answerIndex: 1,
    explanation: "A parable summary should preserve the movement of the story and its meaning.",
  },
  {
    id: "quiz-religious-care",
    track: "religious",
    prompt: "Which response best protects dignity in a care conversation?",
    options: [
      "You should fix this immediately.",
      "I know exactly what you need.",
      "Would you like to tell me more about what happened?",
      "This is not a serious problem.",
    ],
    answerIndex: 2,
    explanation: "A gentle question creates space before advice.",
  },
  {
    id: "quiz-religious-testimony",
    track: "religious",
    prompt: "Which structure best fits a short testimony?",
    options: [
      "Before, turning point, change, present practice.",
      "Price, discount, login, logout.",
      "Only a list of adjectives.",
      "Question, question, question, no answer.",
    ],
    answerIndex: 0,
    explanation: "A testimony becomes clearer when experience is organized in stages.",
  },
  {
    id: "quiz-religious-community-language",
    track: "religious",
    prompt: "Which welcome line sounds warm and clear?",
    options: [
      "You must join every group today.",
      "We are glad you are here; would you like help finding a seat?",
      "Why are you late?",
      "This place is difficult for visitors.",
    ],
    answerIndex: 1,
    explanation: "It is welcoming, practical, and respectful.",
  },
  {
    id: "quiz-religious-translation",
    track: "religious",
    prompt: "A faithful translation note should mention...",
    options: ["tone, context, and meaning risk", "only the longest word", "the fastest option", "a completely unrelated example"],
    answerIndex: 0,
    explanation: "Translation decisions should protect meaning, tone, and context.",
  },
  {
    id: "quiz-religious-discernment",
    track: "religious",
    prompt: "What does discernment require in the studio model?",
    options: [
      "Fast reaction only.",
      "Fact, feeling, counsel, and a wise next step.",
      "Ignoring feedback.",
      "Memorizing one phrase without context.",
    ],
    answerIndex: 1,
    explanation: "Discernment is modeled as careful judgment, not quick reaction.",
  },
];

const lexicalQuizQuestions: EvaQuizQuestion[] = [
  {
    id: "quiz-lexical-calling",
    track: "lexical",
    prompt: "Which collocation is most natural?",
    options: ["do a calling", "clarify a calling", "eat a calling", "cancel a calling"],
    answerIndex: 1,
    explanation: "'Clarify a calling' is a natural phrase for understanding purpose.",
  },
  {
    id: "quiz-lexical-discernment",
    track: "lexical",
    prompt: "Which phrase is a natural collocation?",
    options: ["spiritual discernment", "eat discernment", "heavy discernmenting", "cancel discernment"],
    answerIndex: 0,
    explanation: "'Spiritual discernment' is a natural phrase for wise judgment in faith contexts.",
  },
  {
    id: "quiz-lexical-reverence",
    track: "lexical",
    prompt: "Which phrase best matches 'reverence'?",
    options: ["deep respect", "quick payment", "random habit", "grammar deletion"],
    answerIndex: 0,
    explanation: "Reverence means deep respect shown through attitude or action.",
  },
  {
    id: "quiz-lexical-intercession",
    track: "lexical",
    prompt: "Intercession is closest in meaning to...",
    options: ["prayer on behalf of another person", "a reading speed", "a punctuation mark", "a browser tab"],
    answerIndex: 0,
    explanation: "Intercession is prayer or action for someone else.",
  },
  {
    id: "quiz-lexical-exegesis",
    track: "lexical",
    prompt: "What does 'exegesis' mean in this studio?",
    options: ["random speech practice", "careful explanation of a text", "a type of payment", "a pronunciation error"],
    answerIndex: 1,
    explanation: "Exegesis is careful explanation based on text and context.",
  },
  {
    id: "quiz-lexical-testimony",
    track: "lexical",
    prompt: "Which collocation is most natural?",
    options: ["share a testimony", "drink a testimony", "delete a testimony", "sleep a testimony"],
    answerIndex: 0,
    explanation: "'Share a testimony' is the natural collocation.",
  },
  {
    id: "quiz-lexical-fellowship",
    track: "lexical",
    prompt: "In this booklet, fellowship means...",
    options: [
      "supportive spiritual community and shared life",
      "a grammar error",
      "a private payment code",
      "a random list of words",
    ],
    answerIndex: 0,
    explanation: "Fellowship is more than friendship; it carries community and shared faith.",
  },
  {
    id: "quiz-lexical-compassion",
    track: "lexical",
    prompt: "Which phrase is most natural?",
    options: ["show compassion", "make compassioning", "do the compassion", "cancel compassion"],
    answerIndex: 0,
    explanation: "'Show compassion' is a standard collocation.",
  },
  {
    id: "quiz-lexical-stewardship",
    track: "lexical",
    prompt: "Stewardship is best explained as...",
    options: [
      "responsible care for something entrusted to you",
      "a fast exam trick",
      "a type of audio error",
      "a phrase with no practical use",
    ],
    answerIndex: 0,
    explanation: "Stewardship is responsible care for time, gifts, money, learning, or service.",
  },
  {
    id: "quiz-lexical-cohesion",
    track: "lexical",
    prompt: "Cohesion mainly helps a paragraph...",
    options: ["be longer without meaning", "connect smoothly", "avoid all grammar", "hide the main idea"],
    answerIndex: 1,
    explanation: "Cohesion is the smooth connection between ideas and sentences.",
  },
];

export const evaQuizQuestions: EvaQuizQuestion[] = [...grammarQuizQuestions, ...religiousQuizQuestions, ...lexicalQuizQuestions];

export const evaSkillModules = [...evaGrammarModules, ...evaReligiousModules];
