export type EvaMaterialTrack = "reading" | "writing" | "listening" | "pronunciation" | "teacher";

export type EvaMaterialQuestion = {
  id: string;
  type: string;
  prompt: string;
  options: string[];
  answerIndex: number;
  rationale: string;
};

export type EvaSourceProvenance = {
  sourceId: string;
  title: string;
  url: string;
  licenseName: string;
  licenseUrl: string;
  attribution: string;
  usage: "original" | "copied-verbatim" | "adapted";
  note: string;
};

export type EvaMaterialSourceDocument = {
  id: string;
  title: string;
  privacy: "owned-original" | "private" | "public-domain" | "reference-only";
  sourceUrl: string;
  licenseName: string;
  licenseUrl: string;
  attribution: string;
  textCharacters: number | null;
};

export type EvaMaterialItem = {
  id: string;
  track: EvaMaterialTrack;
  exam: "IELTS" | "TOEFL" | "EduPocket";
  skill: "reading" | "writing" | "listening" | "pronunciation" | "teacher-feedback";
  title: string;
  level: "B1" | "B2";
  timeLimitMinutes: number;
  summary: string;
  sourceUse: string;
  sourceTypeTargets: string[];
  passage?: string;
  prompt?: string;
  ttsScript?: string;
  questions: EvaMaterialQuestion[];
  routine: string[];
  rubric: string[];
  visualAsset?: string;
  sourceProvenance?: EvaSourceProvenance[];
  tags: string[];
  localeNotes: {
    en: string;
    fa: string;
  };
};

export const evaMaterialSourceDocuments: EvaMaterialSourceDocument[] = [
  {
    id: "edupocket-original-eva-material-bank",
    title: "EduPocket Original Eva Practice Bank",
    privacy: "owned-original",
    sourceUrl: "https://edupocket.org/eva-digital-booklet",
    licenseName: "EduPocket owned original material",
    licenseUrl: "https://edupocket.org/eva-digital-booklet",
    attribution: "Original practice content by Ali Esfandiari Rad for EduPocket.",
    textCharacters: null,
  },
  {
    id: "world-english-bible-public-domain",
    title: "World English Bible",
    privacy: "public-domain",
    sourceUrl: "https://eBible.org/web/",
    licenseName: "Public Domain",
    licenseUrl: "https://eBible.org/engwebp/copyright.htm",
    attribution: "World English Bible, public domain text by eBible.org.",
    textCharacters: null,
  },
];

const edupocketOriginalProvenance: EvaSourceProvenance = {
  sourceId: "edupocket-original-eva-material-bank",
  title: "EduPocket Original Eva Practice Bank",
  url: "https://edupocket.org/eva-digital-booklet",
  licenseName: "EduPocket owned original material",
  licenseUrl: "https://edupocket.org/eva-digital-booklet",
  attribution: "Original practice content by Ali Esfandiari Rad for EduPocket.",
  usage: "original",
  note: "Passage, prompt, answer key, rationale, routine, and rubric were created for this product.",
};

const worldEnglishBibleProvenance: EvaSourceProvenance = {
  sourceId: "world-english-bible-public-domain",
  title: "World English Bible",
  url: "https://eBible.org/web/",
  licenseName: "Public Domain",
  licenseUrl: "https://eBible.org/engwebp/copyright.htm",
  attribution: "World English Bible, public domain text by eBible.org.",
  usage: "copied-verbatim",
  note: "Bible text is copied verbatim from the public-domain World English Bible; EduPocket exercises, questions, rationales, and rubrics are original.",
};

export const evaMaterialSourcePolicy = [
  {
    label: "Original EduPocket material",
    note: "The practice passages, prompts, answer keys, rationales, rubrics, visual assets, and TTS scripts in this file are original EduPocket/Eva material.",
  },
  {
    label: "Source workbook conversion",
    note: "Additional chapter packs are generated from the private Eva source booklet and remain inside the premium studio flow.",
  },
  {
    label: "Exam-owner safety",
    note: "The tasks are IELTS/TOEFL-style by skill family only. They do not copy IELTS, TOEFL, ETS, British Council, test-english, or other exam-prep passages.",
  },
  {
    label: "Public-domain references",
    note: "Public-domain passages can be copied into premium materials only when source, license, and attribution are recorded for the active material.",
  },
  {
    label: "TTS implementation",
    note: "Pronunciation and listening scripts are designed for the browser Web Speech API, so no paid audio API is required for the premium study flow.",
  },
];

export const evaReadingMaterials: EvaMaterialItem[] = [
  {
    id: "reading-microlearning-durable-progress",
    track: "reading",
    exam: "IELTS",
    skill: "reading",
    title: "Microlearning and durable progress",
    level: "B2",
    timeLimitMinutes: 18,
    summary: "A short academic passage about why small study cycles can outperform long passive sessions.",
    sourceUse: "Best linked to progress pages, reading labs, and review queue pages from the original booklet.",
    sourceTypeTargets: ["reading-lab", "reading-lab-rc", "progress"],
    visualAsset: "/images/materials/eva/eva-reading-route.svg",
    passage:
      "Microlearning is often misunderstood as a shortcut. In a serious study system, it is not a way to do less work; it is a way to protect attention long enough for useful work to happen. A ten-minute activity can be weak if it is isolated, but it can be powerful when it belongs to a cycle: preview, attempt, feedback, revision, and delayed review. The important feature is not the size of the lesson but the evidence it produces. A learner who writes one corrected paragraph, repeats five difficult words, and adds two weak items to a review queue has created more usable evidence than a learner who reads twenty pages without a decision. Digital booklets can make this evidence visible by recording each attempt and connecting it to the next step.",
    prompt: "Answer the questions. The passage is original EduPocket material and follows IELTS-style reading demands.",
    questions: [
      {
        id: "r-mdp-q1",
        type: "True / False / Not Given",
        prompt: "The passage says microlearning is valuable mainly because learners do less work.",
        options: ["True", "False", "Not Given"],
        answerIndex: 1,
        rationale: "The passage says microlearning is not a way to do less work but a way to protect attention.",
      },
      {
        id: "r-mdp-q2",
        type: "Multiple choice",
        prompt: "Which sequence best represents the cycle described in the passage?",
        options: ["Read, memorize, ignore", "Preview, attempt, feedback, revision, delayed review", "Buy, download, display", "Listen, copy, submit, forget"],
        answerIndex: 1,
        rationale: "The cycle is named directly in the second sentence.",
      },
      {
        id: "r-mdp-q3",
        type: "Inference",
        prompt: "Why does the author contrast one corrected paragraph with twenty unread decisions?",
        options: ["To argue that evidence matters more than page count", "To reject reading entirely", "To recommend only speaking practice", "To show that digital tools remove effort"],
        answerIndex: 0,
        rationale: "The contrast supports the point that visible evidence is more useful than passive volume.",
      },
      {
        id: "r-mdp-q4",
        type: "Vocabulary in context",
        prompt: "In the passage, 'usable evidence' is closest in meaning to...",
        options: ["decorative proof", "trackable learning output", "private payment data", "a copied answer"],
        answerIndex: 1,
        rationale: "The evidence is something the system can record and use to choose the next step.",
      },
    ],
    routine: ["Skim for the author's definition of microlearning.", "Underline every study output mentioned.", "Answer, then write a one-sentence evidence rule."],
    rubric: ["main idea", "detail matching", "inference", "vocabulary in context"],
    tags: ["microlearning", "review queue", "learning evidence", "IELTS reading"],
    localeNotes: {
      en: "Use this when Eva needs to connect study discipline with measurable progress.",
      fa: "براي وقتي كه زبان آموز بايد بفهمد پيشرفت واقعي يعني خروجي قابل پيگيري، نه فقط خواندن بي هدف.",
    },
  },
  {
    id: "reading-ai-feedback-second-reader",
    track: "reading",
    exam: "TOEFL",
    skill: "reading",
    title: "AI feedback as a second reader",
    level: "B2",
    timeLimitMinutes: 16,
    summary: "A TOEFL-style passage about using AI feedback without replacing teacher judgment.",
    sourceUse: "Connects to AI-augmented learning, writing vault, and teacher notes.",
    sourceTypeTargets: ["progress", "journal", "reading-lab-rc"],
    visualAsset: "/images/materials/eva/eva-writing-vault.svg",
    passage:
      "AI feedback is most useful when it acts as a second reader rather than a final judge. A system can notice repeated grammar patterns, missing examples, or vague claims, but it cannot fully understand the learner's intention, emotional state, or long-term goals. For this reason, strong learners use AI comments as a draft lens. They ask what the machine noticed, decide which comments are relevant, and then bring the revised draft to a teacher or mentor. This order keeps the learner active. In a premium study portal, AI-augmented routines can be built with checklists, rubrics, and stored teacher notes even before an external model is connected.",
    prompt: "Answer the questions. The passage is original EduPocket material and follows TOEFL-style reading demands.",
    questions: [
      {
        id: "r-ai-q1",
        type: "Factual information",
        prompt: "According to the passage, what can AI feedback notice?",
        options: ["Repeated grammar patterns", "A learner's complete emotional state", "All long-term goals", "The final grade for every essay"],
        answerIndex: 0,
        rationale: "Repeated grammar patterns are listed as a useful thing AI can notice.",
      },
      {
        id: "r-ai-q2",
        type: "Rhetorical purpose",
        prompt: "Why does the author describe AI as a 'draft lens'?",
        options: ["To show it helps learners inspect drafts before final feedback", "To claim it replaces all human teaching", "To explain camera technology", "To say drafts should be hidden"],
        answerIndex: 0,
        rationale: "The metaphor presents AI as a tool for looking at a draft, not as the final authority.",
      },
      {
        id: "r-ai-q3",
        type: "Inference",
        prompt: "What would the author probably support?",
        options: ["A learner rejecting every AI comment without reading it", "A learner using a rubric before asking a teacher for feedback", "A teacher never reading student drafts", "A portal deleting stored notes"],
        answerIndex: 1,
        rationale: "The passage supports checklists, rubrics, teacher notes, and active learner decisions.",
      },
      {
        id: "r-ai-q4",
        type: "Vocabulary in context",
        prompt: "In the passage, 'relevant' is closest in meaning to...",
        options: ["useful for the current purpose", "expensive", "automatic", "grammatically impossible"],
        answerIndex: 0,
        rationale: "Learners decide which AI comments are useful for their draft and goals.",
      },
    ],
    routine: ["Read for the author's position.", "Separate what AI can notice from what humans judge better.", "Write one safe rule for using automated feedback."],
    rubric: ["factual detail", "rhetorical purpose", "inference", "vocabulary"],
    tags: ["AI feedback", "teacher lens", "writing vault", "TOEFL reading"],
    localeNotes: {
      en: "Use this before a writing vault review so the learner understands the feedback hierarchy.",
      fa: "براي قبل از بازبيني Writing Vault مناسب است تا زبان آموز فرق بازخورد ماشين و معلم را بداند.",
    },
  },
  {
    id: "reading-review-queue-rereading",
    track: "reading",
    exam: "IELTS",
    skill: "reading",
    title: "Why review queues beat rereading",
    level: "B1",
    timeLimitMinutes: 14,
    summary: "A practical reading passage on spaced review and weak-skill tracking.",
    sourceUse: "Connects directly to review queue, weak skill map, and page completion.",
    sourceTypeTargets: ["progress", "chapter-quiz", "journal"],
    passage:
      "Many learners reread the same page because it feels safe. Rereading can be useful, but it often hides the exact problem. A review queue works differently. It asks the learner to name the weak item: a word, a tense, a connector, a sentence pattern, or an unanswered question. Once the weak item has a name, the next review becomes smaller and clearer. The learner does not need to repeat the whole page every time. Instead, the learner returns to the point where meaning broke down. This saves energy and makes improvement easier to explain to a teacher.",
    prompt: "Answer the questions. The passage is original EduPocket material and follows IELTS-style reading demands.",
    questions: [
      {
        id: "r-rq-q1",
        type: "Multiple choice",
        prompt: "What problem can rereading hide?",
        options: ["The exact weak point", "The title of the page", "The teacher's name", "The price of the product"],
        answerIndex: 0,
        rationale: "The passage says rereading can hide the exact problem.",
      },
      {
        id: "r-rq-q2",
        type: "Sentence completion",
        prompt: "A review queue asks the learner to name...",
        options: ["the weak item", "the website color", "the payment method", "the final certificate"],
        answerIndex: 0,
        rationale: "The weak item is named in the passage as the central action.",
      },
      {
        id: "r-rq-q3",
        type: "True / False / Not Given",
        prompt: "The passage says learners must repeat the whole page every time.",
        options: ["True", "False", "Not Given"],
        answerIndex: 1,
        rationale: "The passage says the learner does not need to repeat the whole page every time.",
      },
    ],
    routine: ["Find the problem with rereading.", "List the examples of weak items.", "Add one current weak item to review."],
    rubric: ["main idea", "detail", "negative claim recognition"],
    tags: ["review queue", "weak skill map", "IELTS reading"],
    localeNotes: {
      en: "Use this when the learner keeps rereading but cannot explain the mistake.",
      fa: "براي وقتي كه زبان آموز فقط دوباره خواني مي كند اما نقطه ضعف را نام گذاري نمي كند.",
    },
  },
  {
    id: "reading-transfer-digital-notebooks",
    track: "reading",
    exam: "TOEFL",
    skill: "reading",
    title: "Digital notebooks and transfer",
    level: "B2",
    timeLimitMinutes: 17,
    summary: "A TOEFL-style passage about moving knowledge from one context to another.",
    sourceUse: "Useful for translation, exegesis, and portfolio sections.",
    sourceTypeTargets: ["translation", "exegesis", "progress"],
    passage:
      "A digital notebook becomes valuable when it supports transfer. Transfer means using knowledge from one situation in another situation. For example, a learner may first study a connector in a grammar exercise, then use the same connector in a reading summary, a translation note, and an IELTS-style paragraph. The item is no longer trapped inside one page. It has become portable. Teachers can encourage transfer by asking learners to tag evidence, compare drafts, and revisit old notes before starting a new task. The goal is not to collect more notes; the goal is to make old notes work in new contexts.",
    prompt: "Answer the questions. The passage is original EduPocket material and follows TOEFL-style reading demands.",
    questions: [
      {
        id: "r-dn-q1",
        type: "Factual information",
        prompt: "What does transfer mean in the passage?",
        options: ["Using knowledge in another situation", "Deleting old notes", "Changing the font", "Buying a second course"],
        answerIndex: 0,
        rationale: "The passage defines transfer directly.",
      },
      {
        id: "r-dn-q2",
        type: "Inference",
        prompt: "What is a 'portable' item?",
        options: ["A learning item usable beyond its first page", "A phone charger", "A hidden private file", "A copied answer key"],
        answerIndex: 0,
        rationale: "The item moves across grammar, summary, translation, and paragraph tasks.",
      },
      {
        id: "r-dn-q3",
        type: "Rhetorical purpose",
        prompt: "Why does the author mention tags and draft comparison?",
        options: ["To show teacher actions that support transfer", "To advertise a social network", "To reject notebooks", "To replace every lesson with audio"],
        answerIndex: 0,
        rationale: "Tags and comparisons are teacher-supported ways to make notes reusable.",
      },
    ],
    routine: ["Define transfer.", "Trace one connector across three tasks.", "Write a transfer sentence from today's page."],
    rubric: ["definition", "inference", "purpose"],
    tags: ["transfer", "digital notebook", "TOEFL reading"],
    localeNotes: {
      en: "Use after grammar work so the learner reuses a pattern in reading and writing.",
      fa: "بعد از كار گرامر خوب است، چون الگو را از يك صفحه به چند مهارت منتقل مي كند.",
    },
  },
  {
    id: "reading-attention-study-ritual",
    track: "reading",
    exam: "IELTS",
    skill: "reading",
    title: "Attention, ritual, and study rooms",
    level: "B2",
    timeLimitMinutes: 18,
    summary: "A calm academic passage about environmental cues and learning attention.",
    sourceUse: "Pairs with study habit systems, journal prompts, and weekly reflection.",
    sourceTypeTargets: ["journal", "progress", "enrichment"],
    passage:
      "Attention is not only a personal quality; it is also shaped by surroundings. A learner who studies in the same quiet corner, begins with the same two-minute preview, and ends by saving one note is building a ritual. The ritual does not learn for the student, but it reduces the number of decisions required to begin. This matters because many learners lose energy before the task starts. A premium digital booklet can support ritual by making the entry point predictable: open the portal, choose the next step, read or listen, produce evidence, and close with a review decision.",
    prompt: "Answer the questions. The passage is original EduPocket material and follows IELTS-style reading demands.",
    questions: [
      {
        id: "r-asr-q1",
        type: "Multiple choice",
        prompt: "What is the main benefit of a study ritual in the passage?",
        options: ["It reduces decisions required to begin", "It removes the need to study", "It guarantees a perfect score", "It replaces all teacher feedback"],
        answerIndex: 0,
        rationale: "The passage says ritual reduces the number of decisions required to begin.",
      },
      {
        id: "r-asr-q2",
        type: "True / False / Not Given",
        prompt: "The author says the ritual learns for the student.",
        options: ["True", "False", "Not Given"],
        answerIndex: 1,
        rationale: "The passage states the ritual does not learn for the student.",
      },
      {
        id: "r-asr-q3",
        type: "Sentence completion",
        prompt: "The predictable portal sequence ends with...",
        options: ["a review decision", "a public download", "a new payment", "a deleted note"],
        answerIndex: 0,
        rationale: "The final sentence ends the sequence with a review decision.",
      },
    ],
    routine: ["Identify the ritual.", "Explain why the first decision is important.", "Design your own two-minute entry routine."],
    rubric: ["main idea", "detail", "sequence"],
    tags: ["attention", "study ritual", "IELTS reading"],
    localeNotes: {
      en: "Use on low-energy days to make study feel easy to start.",
      fa: "براي روزهاي كم انرژي خوب است چون شروع درس را ساده و قابل پيش بيني مي كند.",
    },
  },
  {
    id: "reading-teacher-notes-evidence",
    track: "reading",
    exam: "TOEFL",
    skill: "reading",
    title: "Teacher notes and evidence",
    level: "B2",
    timeLimitMinutes: 16,
    summary: "A TOEFL-style passage about feedback that names the next action.",
    sourceUse: "Pairs with Teacher Lens, teacher notes, and writing vault review.",
    sourceTypeTargets: ["progress", "journal", "chapter-quiz"],
    passage:
      "Feedback is most useful when it names evidence and gives a next action. A note such as 'good job' may encourage a learner, but it does not show what to repeat. A stronger note says, 'Your topic sentence is clear, but your example is too general. Add one specific event and explain its result.' This kind of note teaches the learner how to inspect future work. It also helps the teacher track whether advice is being used. When a digital studio stores teacher notes beside drafts, the feedback becomes part of the learner's review path rather than a comment that disappears after one lesson.",
    prompt: "Answer the questions. The passage is original EduPocket material and follows TOEFL-style reading demands.",
    questions: [
      {
        id: "r-tne-q1",
        type: "Factual information",
        prompt: "What should useful feedback name?",
        options: ["Evidence and a next action", "Only the learner's name", "The website host", "A random quote"],
        answerIndex: 0,
        rationale: "The first sentence gives the answer directly.",
      },
      {
        id: "r-tne-q2",
        type: "Inference",
        prompt: "Why is 'good job' weaker than the longer example?",
        options: ["It does not show what to repeat or fix", "It is too formal", "It contains too many examples", "It requires a timer"],
        answerIndex: 0,
        rationale: "The passage says it may encourage but does not show what to repeat.",
      },
      {
        id: "r-tne-q3",
        type: "Rhetorical purpose",
        prompt: "Why does the author mention storing teacher notes beside drafts?",
        options: ["To show how feedback becomes part of review", "To argue that drafts should never change", "To describe a payment receipt", "To reject teacher feedback"],
        answerIndex: 0,
        rationale: "The final sentence says stored feedback becomes part of the review path.",
      },
    ],
    routine: ["Compare vague and specific feedback.", "Write one next-action note.", "Add that note to a weak draft."],
    rubric: ["detail", "inference", "purpose"],
    tags: ["teacher notes", "feedback", "TOEFL reading"],
    localeNotes: {
      en: "Use before Ali reviews Eva or Elham so feedback stays actionable.",
      fa: "قبل از بازبيني معلم مناسب است چون بازخورد را تبديل به اقدام بعدي مي كند.",
    },
  },
  {
    id: "reading-web-matthew-anxiety-attention",
    track: "reading",
    exam: "IELTS",
    skill: "reading",
    title: "Public-domain reading: attention and anxiety",
    level: "B2",
    timeLimitMinutes: 18,
    summary: "A public-domain WEB passage converted into IELTS-style reading practice with original EduPocket questions.",
    sourceUse: "Uses copied public-domain Bible text as a reading passage, then connects it to reflection, vocabulary, and review decisions.",
    sourceTypeTargets: ["chapter-reading", "exegesis", "reading-lab", "enrichment"],
    passage:
      "Therefore I tell you, don't be anxious for your life: what you will eat, or what you will drink; nor yet for your body, what you will wear. Isn't life more than food, and the body more than clothing? See the birds of the sky, that they don't sow, neither do they reap, nor gather into barns. Your heavenly Father feeds them. Aren't you of much more value than they? Which of you by being anxious can add one moment to his lifespan? Why are you anxious about clothing? Consider the lilies of the field, how they grow. They don't toil, neither do they spin, yet I tell you that even Solomon in all his glory was not dressed like one of these. But if God so clothes the grass of the field, which today exists, and tomorrow is thrown into the oven, won't he much more clothe you, you of little faith? Therefore don't be anxious, saying, 'What will we eat?', 'What will we drink?' or, 'What will we wear?' For the Gentiles seek after all these things; for your heavenly Father knows that you need all these things. But seek first God's Kingdom and his righteousness; and all these things will be given to you as well. Therefore don't be anxious for tomorrow, for tomorrow will be anxious for itself. Each day's own evil is sufficient.",
    prompt: "Answer the questions, then write one evidence sentence about how attention is redirected in the passage.",
    questions: [
      {
        id: "r-web-matthew-q1",
        type: "Main idea",
        prompt: "What is the main movement of the passage?",
        options: ["From anxiety toward trust and ordered attention", "From travel planning toward a weather report", "From grammar rules toward exam registration", "From clothing descriptions toward shopping advice only"],
        answerIndex: 0,
        rationale: "The repeated command not to be anxious is paired with examples that redirect attention toward trust and priority.",
      },
      {
        id: "r-web-matthew-q2",
        type: "Detail",
        prompt: "Which natural examples are used as evidence?",
        options: ["Birds and lilies", "Rivers and mountains", "Stars and clouds", "Seeds and stones only"],
        answerIndex: 0,
        rationale: "The passage explicitly mentions birds of the sky and lilies of the field.",
      },
      {
        id: "r-web-matthew-q3",
        type: "Inference",
        prompt: "Why does the passage ask several rhetorical questions?",
        options: ["To make the reader examine the usefulness of anxiety", "To give a shopping list", "To introduce unrelated historical dates", "To avoid making a claim"],
        answerIndex: 0,
        rationale: "The questions challenge the reader to compare anxiety with trust, value, and priority.",
      },
      {
        id: "r-web-matthew-q4",
        type: "Vocabulary in context",
        prompt: "In this passage, 'seek first' is closest to...",
        options: ["give priority to", "look quickly at", "search online for", "delay every decision"],
        answerIndex: 0,
        rationale: "The phrase is about priority and ordering attention.",
      },
    ],
    routine: ["Mark every repeated command.", "Underline the natural examples.", "Answer the questions before opening the rationale.", "Save one reflection sentence in the Writing Vault."],
    rubric: ["main idea", "detail recognition", "inference", "lexical meaning"],
    sourceProvenance: [worldEnglishBibleProvenance],
    tags: ["public domain", "WEB", "Matthew 6", "anxiety", "attention", "IELTS reading", "religious context"],
    localeNotes: {
      en: "Use this for a serious reading session where spiritual meaning and academic reading skills meet.",
      fa: "برای تمرین جدی reading؛ هم معنا و هم مهارت آزمونی را همزمان قابل پیگیری می‌کند.",
    },
  },
  {
    id: "reading-web-romans-transformed-service",
    track: "reading",
    exam: "TOEFL",
    skill: "reading",
    title: "Public-domain reading: transformation and service",
    level: "B2",
    timeLimitMinutes: 16,
    summary: "A TOEFL-style reading pack built on a public-domain WEB passage about renewal, humility, and service.",
    sourceUse: "Uses public-domain Bible text as the base text for inference, rhetorical-purpose, and vocabulary practice.",
    sourceTypeTargets: ["exegesis", "scenario", "chapter-reading", "translation"],
    passage:
      "Therefore I urge you, brothers, by the mercies of God, to present your bodies a living sacrifice, holy, acceptable to God, which is your spiritual service. Don't be conformed to this world, but be transformed by the renewing of your mind, so that you may prove what is the good, well-pleasing, and perfect will of God. For I say through the grace that was given me, to every man who is among you, not to think of himself more highly than he ought to think; but to think reasonably, as God has apportioned to each person a measure of faith. For even as we have many members in one body, and all the members don't have the same function, so we, who are many, are one body in Christ, and individually members of one another. Having gifts differing according to the grace that was given to us, if prophecy, let us prophesy according to the proportion of our faith; or service, let us give ourselves to service; or he who teaches, to his teaching; or he who exhorts, to his exhorting; he who gives, let him do it with generosity; he who rules, with diligence; he who shows mercy, with cheerfulness.",
    prompt: "Answer the questions, then write one ministry-ready sentence that uses 'transformed', 'service', or 'diligence' naturally.",
    questions: [
      {
        id: "r-web-romans-q1",
        type: "Rhetorical purpose",
        prompt: "Why does the passage mention different gifts?",
        options: ["To show that service has different functions inside one body", "To argue that only one person should serve", "To list unrelated job titles", "To avoid the topic of humility"],
        answerIndex: 0,
        rationale: "The passage connects many members, different functions, and different gifts inside one body.",
      },
      {
        id: "r-web-romans-q2",
        type: "Factual information",
        prompt: "According to the passage, what should be renewed?",
        options: ["The mind", "The building", "The payment plan", "The website menu"],
        answerIndex: 0,
        rationale: "The text says to be transformed by the renewing of the mind.",
      },
      {
        id: "r-web-romans-q3",
        type: "Inference",
        prompt: "What attitude does the passage discourage?",
        options: ["Thinking too highly of oneself", "Serving with diligence", "Showing mercy", "Teaching carefully"],
        answerIndex: 0,
        rationale: "The passage explicitly tells each person not to think of himself more highly than he ought.",
      },
      {
        id: "r-web-romans-q4",
        type: "Vocabulary in context",
        prompt: "In this passage, 'function' is closest to...",
        options: ["role or purpose", "mathematical formula only", "private password", "unrelated decoration"],
        answerIndex: 0,
        rationale: "The body metaphor uses function to mean the role or purpose of each member.",
      },
    ],
    routine: ["Identify the main command.", "Map each gift to a service action.", "Answer the questions.", "Add one weak word to the review queue."],
    rubric: ["rhetorical purpose", "factual detail", "inference", "vocabulary"],
    sourceProvenance: [worldEnglishBibleProvenance],
    tags: ["public domain", "WEB", "Romans 12", "service", "TOEFL reading", "lexical resource"],
    localeNotes: {
      en: "Use when Eva needs reading practice that also builds usable ministry vocabulary.",
      fa: "برای وقتی که Eva باید هم reading تمرین کند هم واژگان قابل استفاده برای خدمت یاد بگیرد.",
    },
  },
];

export const evaWritingMaterials: EvaMaterialItem[] = [
  {
    id: "writing-ielts-ai-before-teacher",
    track: "writing",
    exam: "IELTS",
    skill: "writing",
    title: "AI feedback before teacher feedback",
    level: "B2",
    timeLimitMinutes: 25,
    summary: "IELTS-style Task 2 practice about responsible AI use in language learning.",
    sourceUse: "Connects to AI feedback reading, writing vault, and teacher notes.",
    sourceTypeTargets: ["journal", "progress", "reading-lab-rc"],
    visualAsset: "/images/materials/eva/eva-writing-vault.svg",
    prompt: "Some language learners use AI feedback before sending their writing to a teacher. Others believe teacher feedback should always come first. Discuss both views and give your own opinion.",
    questions: [],
    routine: ["Plan both views in four bullets.", "Write a clear opinion in the introduction.", "Use one example from your own study routine.", "Revise topic sentences before saving."],
    rubric: ["task response", "coherence and cohesion", "lexical resource", "grammar range and accuracy"],
    tags: ["IELTS writing", "AI feedback", "teacher notes"],
    localeNotes: {
      en: "Use after the AI second-reader passage so the learner can turn reading into writing.",
      fa: "بعد از متن AI feedback مناسب است تا خواندن به Writing تبديل شود.",
    },
  },
  {
    id: "writing-ielts-weekly-review-process",
    track: "writing",
    exam: "IELTS",
    skill: "writing",
    title: "Weekly review cycle process",
    level: "B1",
    timeLimitMinutes: 20,
    summary: "IELTS Task 1 process practice based on the studio review loop.",
    sourceUse: "Connects to Coverage Meter, Smart Next Step, and review queue.",
    sourceTypeTargets: ["progress", "chapter-quiz"],
    prompt:
      "The process shows how a learner uses a weekly review cycle in a digital study portal: choose a weak skill, open related pages, complete one activity, save evidence, receive feedback, and schedule the next review. Summarize the process and describe the main stages.",
    questions: [],
    routine: ["Group the process into beginning, middle, and end.", "Use passive voice where natural.", "Write one overview sentence.", "Avoid listing every step without grouping."],
    rubric: ["overview", "sequence language", "stage grouping", "grammar accuracy"],
    tags: ["IELTS task 1", "process writing", "review cycle"],
    localeNotes: {
      en: "Use to practice process language without needing a copyrighted diagram.",
      fa: "براي تمرين Process Writing بدون نياز به نمودار كپي شده.",
    },
  },
  {
    id: "writing-toefl-discussion-pronunciation",
    track: "writing",
    exam: "TOEFL",
    skill: "writing",
    title: "Pronunciation lab in academic discussion",
    level: "B2",
    timeLimitMinutes: 10,
    summary: "TOEFL Academic Discussion style response about pronunciation practice.",
    sourceUse: "Connects to lexical resource, shadowing, and TTS listened/repeated tracking.",
    sourceTypeTargets: ["listening-speaking", "vocabulary"],
    visualAsset: "/images/materials/eva/eva-pronunciation-lab.svg",
    prompt: "Your class is discussing whether pronunciation practice should be part of every language course. Write a response that states your view, responds to the discussion, and gives one concrete example.",
    questions: [],
    routine: ["State your view in sentence one.", "Add one reason.", "Give one specific learning example.", "End with a practical conclusion."],
    rubric: ["clear position", "development", "example", "academic tone"],
    tags: ["TOEFL writing", "pronunciation", "academic discussion"],
    localeNotes: {
      en: "Use after shadowing work so pronunciation practice becomes written argument.",
      fa: "بعد از Shadowing خوب است، چون تمرين تلفظ را تبديل به استدلال نوشتاري مي كند.",
    },
  },
  {
    id: "writing-toefl-integrated-review-queue",
    track: "writing",
    exam: "TOEFL",
    skill: "writing",
    title: "Integrated response: review queues",
    level: "B2",
    timeLimitMinutes: 20,
    summary: "TOEFL integrated-style writing with an original reading and TTS lecture script.",
    sourceUse: "Connects to reading review queue and listening scripts.",
    sourceTypeTargets: ["reading-lab", "listening-speaking", "progress"],
    passage:
      "A review queue helps learners revisit weak points efficiently. Supporters argue that it saves time because learners return to named problems instead of repeating complete pages. It can also give teachers clearer evidence of progress.",
    ttsScript:
      "The lecture adds that review queues work best when the learner writes a reason for each item. If a word is added only because it feels difficult, the learner may ignore it later. But if the note says, 'I confused although and however in a contrast sentence,' the next review becomes more focused.",
    prompt: "Summarize the points made in the lecture and explain how they add to the reading passage. Do not express your own opinion.",
    questions: [],
    routine: ["Read the passage.", "Listen to the lecture script with TTS.", "Write reading point plus lecture addition.", "Use reporting verbs, not opinion language."],
    rubric: ["source integration", "accuracy", "organization", "language control"],
    tags: ["TOEFL integrated writing", "review queue", "listening"],
    localeNotes: {
      en: "Use as a compact integrated task with browser TTS instead of external audio.",
      fa: "يك Integrated Task كوتاه با TTS مرورگر، بدون نياز به فايل صوتي خارجي.",
    },
  },
  {
    id: "writing-ielts-small-groups",
    track: "writing",
    exam: "IELTS",
    skill: "writing",
    title: "Small groups and independent learning",
    level: "B2",
    timeLimitMinutes: 25,
    summary: "IELTS-style Task 2 prompt on study groups versus independent learning.",
    sourceUse: "Connects to scenario pages, service work, and collaboration.",
    sourceTypeTargets: ["scenario", "journal", "progress"],
    prompt: "Some students learn best in small guided groups, while others make faster progress when they study independently. Discuss both views and give your own opinion.",
    questions: [],
    routine: ["Brainstorm one benefit for each side.", "Choose a balanced opinion.", "Use one connector of contrast and one connector of result.", "Save the final paragraph in the vault."],
    rubric: ["balanced argument", "paragraph control", "connector accuracy", "examples"],
    tags: ["IELTS writing", "study groups", "independent learning"],
    localeNotes: {
      en: "Use when the learner needs a human learning topic that still fits EduPocket.",
      fa: "براي تمرين موضوع انساني و آموزشي كه با هويت EduPocket هماهنگ است.",
    },
  },
  {
    id: "writing-toefl-teacher-notes",
    track: "writing",
    exam: "TOEFL",
    skill: "writing",
    title: "Teacher notes and learner autonomy",
    level: "B2",
    timeLimitMinutes: 10,
    summary: "TOEFL Academic Discussion style response about feedback and autonomy.",
    sourceUse: "Connects to Teacher Lens and feedback templates.",
    sourceTypeTargets: ["journal", "progress"],
    prompt: "Your class is discussing whether detailed teacher notes make students more independent or too dependent on correction. Write your contribution to the discussion.",
    questions: [],
    routine: ["Choose one side.", "Acknowledge the other side briefly.", "Give a concrete example of a useful teacher note.", "End with a learner action."],
    rubric: ["position", "response to issue", "example", "control"],
    tags: ["TOEFL writing", "teacher feedback", "autonomy"],
    localeNotes: {
      en: "Use before Teacher Lens review so the learner understands why feedback must name action.",
      fa: "قبل از Teacher Lens مناسب است چون هدف بازخورد دقيق را روشن مي كند.",
    },
  },
  {
    id: "writing-web-james-listening-response",
    track: "writing",
    exam: "IELTS",
    skill: "writing",
    title: "Public-domain writing: listening before speaking",
    level: "B2",
    timeLimitMinutes: 22,
    summary: "An IELTS-style paragraph task using a public-domain WEB verse as the source idea.",
    sourceUse: "Uses copied public-domain Bible text as the seed text for original writing practice and teacher review.",
    sourceTypeTargets: ["listening-speaking", "scenario", "journal", "translation"],
    passage: "So, then, my beloved brothers, let every man be swift to hear, slow to speak, and slow to anger;",
    prompt: "Use the source sentence as the idea seed. Write one IELTS-style paragraph explaining why listening before speaking can improve learning, teamwork, or ministry communication. Include one concrete example.",
    questions: [],
    routine: ["Copy the source sentence into your notes.", "Underline the three action phrases.", "Write one topic sentence.", "Add one example and one result sentence.", "Save the paragraph in the Writing Vault."],
    rubric: ["topic sentence", "example quality", "cohesion", "grammar range"],
    sourceProvenance: [worldEnglishBibleProvenance],
    tags: ["public domain", "WEB", "James 1", "IELTS writing", "listening", "speaking"],
    localeNotes: {
      en: "Use this when the learner needs a short source-based paragraph that connects faith language with academic writing.",
      fa: "برای تمرین پاراگراف کوتاه و جدی؛ جمله منبع، writing و مهارت ارتباطی را به هم وصل می‌کند.",
    },
  },
];

export const evaListeningMaterials: EvaMaterialItem[] = [
  {
    id: "listening-study-ritual-briefing",
    track: "listening",
    exam: "EduPocket",
    skill: "listening",
    title: "Study ritual briefing",
    level: "B1",
    timeLimitMinutes: 8,
    summary: "A calm TTS briefing for opening a serious study session.",
    sourceUse: "Use before the first page of a study session.",
    sourceTypeTargets: ["progress", "journal"],
    ttsScript: "Open the portal. Choose one source page. Read the title first. Before you answer, say the goal of the activity in one sentence. After you finish, save one piece of evidence and decide whether this page belongs in review.",
    questions: [
      {
        id: "l-sr-q1",
        type: "Listening detail",
        prompt: "What should the learner say before answering?",
        options: ["The goal of the activity", "The price of the booklet", "A random grammar rule", "The teacher's password"],
        answerIndex: 0,
        rationale: "The script asks the learner to say the goal of the activity in one sentence.",
      },
    ],
    routine: ["Listen once.", "Repeat the five actions.", "Open one page and follow the routine."],
    rubric: ["listening for sequence", "shadowing", "study readiness"],
    tags: ["listening", "study ritual", "TTS"],
    localeNotes: {
      en: "Use this as the entry audio for a focused session.",
      fa: "براي شروع يك جلسه متمركز استفاده شود.",
    },
  },
  {
    id: "listening-feedback-conference",
    track: "listening",
    exam: "EduPocket",
    skill: "listening",
    title: "Feedback conference mini-dialogue",
    level: "B2",
    timeLimitMinutes: 9,
    summary: "A two-speaker style TTS script for teacher feedback language.",
    sourceUse: "Pairs with Teacher Lens and writing vault.",
    sourceTypeTargets: ["journal", "progress"],
    ttsScript: "Teacher: Your main idea is clear, but the second example is too general. Learner: Should I add a personal story or an academic example? Teacher: Use one specific event, then explain why it changed the result.",
    questions: [
      {
        id: "l-fc-q1",
        type: "Listening inference",
        prompt: "What does the teacher want the learner to improve?",
        options: ["Specific support", "Website navigation", "Payment method", "Font size"],
        answerIndex: 0,
        rationale: "The teacher asks for one specific event and explanation.",
      },
    ],
    routine: ["Listen.", "Mark teacher advice.", "Rewrite the weak example in your own words."],
    rubric: ["feedback language", "specific support", "response"],
    tags: ["listening", "teacher feedback", "specific examples"],
    localeNotes: {
      en: "Use when teacher comments need to become learner action.",
      fa: "وقتي بازخورد معلم بايد به اقدام عملي تبديل شود.",
    },
  },
  {
    id: "listening-exam-direction-bank",
    track: "listening",
    exam: "EduPocket",
    skill: "listening",
    title: "Exam direction bank",
    level: "B1",
    timeLimitMinutes: 7,
    summary: "Common command language for reading and writing tasks.",
    sourceUse: "Pairs with IELTS/TOEFL exam mode.",
    sourceTypeTargets: ["reading-lab-rc", "chapter-quiz"],
    ttsScript: "Identify the main claim. Choose the best answer. Explain the reason. Compare the two views. Summarize the lecture. Support your opinion with one example. Revise for clarity.",
    questions: [
      {
        id: "l-ed-q1",
        type: "Command recognition",
        prompt: "Which command asks for a personal position?",
        options: ["Support your opinion with one example", "Choose the best answer", "Identify the main claim", "Revise for clarity"],
        answerIndex: 0,
        rationale: "Opinion language asks for the learner's position and support.",
      },
    ],
    routine: ["Listen at normal speed.", "Repeat each command.", "Match each command to reading or writing."],
    rubric: ["command recognition", "pronunciation", "exam readiness"],
    tags: ["exam commands", "listening", "TOEFL", "IELTS"],
    localeNotes: {
      en: "Use before timed practice so directions feel familiar.",
      fa: "قبل از تمرين زمان دار، تا دستورالعمل هاي آزمون آشنا شوند.",
    },
  },
  {
    id: "listening-shadowing-connectors",
    track: "listening",
    exam: "EduPocket",
    skill: "listening",
    title: "Connector shadowing drill",
    level: "B2",
    timeLimitMinutes: 8,
    summary: "A TTS script for rhythm, connectors, and paragraph flow.",
    sourceUse: "Pairs with grammar connectors and paragraph control.",
    sourceTypeTargets: ["grammar-practice", "progress"],
    ttsScript: "Although short lessons are easier to start, they still need a serious review system. Therefore, each activity should end with evidence. However, evidence is useful only when the learner knows what to do next.",
    questions: [
      {
        id: "l-cs-q1",
        type: "Connector function",
        prompt: "Which connector signals contrast?",
        options: ["Although", "Therefore", "Each", "Evidence"],
        answerIndex: 0,
        rationale: "Although introduces contrast.",
      },
    ],
    routine: ["Listen once.", "Shadow at slow speed.", "Circle contrast and result connectors.", "Write a new sentence with both."],
    rubric: ["connector rhythm", "meaning", "shadowing"],
    tags: ["connectors", "shadowing", "pronunciation"],
    localeNotes: {
      en: "Use after the connector grammar module.",
      fa: "بعد از ماژول Connectors استفاده شود.",
    },
  },
  {
    id: "listening-ministry-care-register",
    track: "listening",
    exam: "EduPocket",
    skill: "listening",
    title: "Warm register for care questions",
    level: "B2",
    timeLimitMinutes: 9,
    summary: "A script for soft question formation and caring tone.",
    sourceUse: "Pairs with service scenarios and question formation.",
    sourceTypeTargets: ["scenario", "listening-speaking"],
    ttsScript: "Instead of saying, 'Why did you miss the meeting?' try, 'I noticed you were not able to join us. Is everything all right?' Warm questions give people room to answer honestly.",
    questions: [
      {
        id: "l-mc-q1",
        type: "Tone recognition",
        prompt: "Why is the second question warmer?",
        options: ["It gives room to answer honestly", "It is shorter", "It avoids all grammar", "It removes the listener"],
        answerIndex: 0,
        rationale: "The script explains that warm questions give people room to answer honestly.",
      },
    ],
    routine: ["Listen.", "Repeat the warm question.", "Write two softer versions of direct questions."],
    rubric: ["tone", "question formation", "care language"],
    tags: ["care questions", "register", "speaking solo"],
    localeNotes: {
      en: "Use for service scenarios where tone matters as much as grammar.",
      fa: "براي سناريوهاي ارتباطي كه لحن به اندازه گرامر مهم است.",
    },
  },
  {
    id: "listening-portfolio-reflection",
    track: "listening",
    exam: "EduPocket",
    skill: "listening",
    title: "Portfolio reflection close-out",
    level: "B1",
    timeLimitMinutes: 7,
    summary: "A short closing script for saving evidence and selecting next steps.",
    sourceUse: "Use at the end of a study session.",
    sourceTypeTargets: ["progress", "journal"],
    ttsScript: "Before you close the portal, save one sentence about what improved. Then choose one weak item for review. If you cannot name a weak item, repeat the last question and explain your answer aloud.",
    questions: [
      {
        id: "l-pr-q1",
        type: "Listening detail",
        prompt: "What should the learner save before closing?",
        options: ["One sentence about what improved", "A new password", "A copied passage", "A full invoice"],
        answerIndex: 0,
        rationale: "The first sentence gives the close-out action.",
      },
    ],
    routine: ["Listen.", "Save one improvement sentence.", "Name one weak item or repeat the last question aloud."],
    rubric: ["reflection", "review decision", "speaking recall"],
    tags: ["portfolio", "reflection", "review"],
    localeNotes: {
      en: "Use at the end of each session so progress is not invisible.",
      fa: "در پايان هر جلسه استفاده شود تا پيشرفت پنهان نماند.",
    },
  },
  {
    id: "listening-web-ask-seek-knock",
    track: "listening",
    exam: "EduPocket",
    skill: "listening",
    title: "Public-domain TTS: ask, seek, knock",
    level: "B1",
    timeLimitMinutes: 8,
    summary: "A WEB public-domain listening and shadowing script focused on imperative rhythm and repetition.",
    sourceUse: "Uses copied public-domain Bible text for listening, shadowing, and review-queue practice.",
    sourceTypeTargets: ["listening-speaking", "scenario", "chapter-reading"],
    ttsScript: "Ask, and it will be given you. Seek, and you will find. Knock, and it will be opened for you. For everyone who asks receives. He who seeks finds. To him who knocks it will be opened.",
    questions: [
      {
        id: "l-web-ask-q1",
        type: "Listening sequence",
        prompt: "Which three repeated actions organize the script?",
        options: ["Ask, seek, knock", "Read, pay, close", "Write, erase, hide", "Listen, skip, forget"],
        answerIndex: 0,
        rationale: "The script repeats the three imperatives ask, seek, and knock.",
      },
      {
        id: "l-web-ask-q2",
        type: "Listening detail",
        prompt: "What happens to the one who seeks?",
        options: ["He finds", "He sleeps", "He pays", "He disappears"],
        answerIndex: 0,
        rationale: "The script says that he who seeks finds.",
      },
    ],
    routine: ["Listen once at normal speed.", "Repeat each imperative pair.", "Shadow the whole script slowly.", "Mark one pronunciation difficulty for review."],
    rubric: ["sequence recognition", "imperative rhythm", "shadowing clarity"],
    sourceProvenance: [worldEnglishBibleProvenance],
    tags: ["public domain", "WEB", "Matthew 7", "listening", "shadowing", "imperatives"],
    localeNotes: {
      en: "Use as a short audio ritual for repetition, rhythm, and confidence.",
      fa: "برای تمرین کوتاه شنیداری؛ تکرار، ریتم و اعتماد به نفس را با هم می‌سازد.",
    },
  },
];

export const evaPronunciationMaterials: EvaMaterialItem[] = [
  {
    id: "pronunciation-responsibility",
    track: "pronunciation",
    exam: "EduPocket",
    skill: "pronunciation",
    title: "responsibility /rɪˌspɑːn.səˈbɪl.ə.ti/",
    level: "B2",
    timeLimitMinutes: 6,
    summary: "Stress and syllable control for a high-value academic word.",
    sourceUse: "Pairs with writing and teacher-feedback tasks.",
    sourceTypeTargets: ["vocabulary", "progress"],
    visualAsset: "/images/materials/eva/eva-pronunciation-lab.svg",
    ttsScript: "responsibility. Personal responsibility. A teacher note can increase learner responsibility.",
    questions: [],
    routine: ["Tap Listen.", "Mark the main stress before BIL.", "Repeat three times slowly.", "Use it in one sentence."],
    rubric: ["word stress", "syllable clarity", "sentence use"],
    tags: ["stress", "academic vocabulary", "pronunciation"],
    localeNotes: {
      en: "Useful for writing arguments about learning habits and autonomy.",
      fa: "براي نوشتن درباره عادت هاي يادگيري و مسئوليت فردي مفيد است.",
    },
  },
  {
    id: "pronunciation-evidence",
    track: "pronunciation",
    exam: "EduPocket",
    skill: "pronunciation",
    title: "evidence /ˈev.ə.dəns/",
    level: "B1",
    timeLimitMinutes: 5,
    summary: "A short drill for a core EduPocket tracking word.",
    sourceUse: "Pairs with Coverage Meter and Writing Vault.",
    sourceTypeTargets: ["progress", "journal"],
    ttsScript: "evidence. learning evidence. Save one piece of evidence before you close the portal.",
    questions: [],
    routine: ["Listen.", "Repeat the first syllable clearly.", "Shadow the full sentence.", "Mark as mastered."],
    rubric: ["initial stress", "clear vowels", "shadowing"],
    tags: ["evidence", "tracking", "pronunciation"],
    localeNotes: {
      en: "Core word for explaining why the portal tracks output.",
      fa: "واژه كليدي براي توضيح اينكه چرا پورتال خروجي را پيگيري مي كند.",
    },
  },
  {
    id: "pronunciation-coherence",
    track: "pronunciation",
    exam: "EduPocket",
    skill: "pronunciation",
    title: "coherence /koʊˈhɪr.əns/",
    level: "B2",
    timeLimitMinutes: 6,
    summary: "IELTS/TOEFL writing-rubric pronunciation and meaning drill.",
    sourceUse: "Pairs with paragraph control and writing rubrics.",
    sourceTypeTargets: ["grammar-practice", "progress"],
    ttsScript: "coherence. coherence and cohesion. The paragraph has coherence because every sentence supports one main idea.",
    questions: [],
    routine: ["Listen.", "Notice the stress on HEER.", "Repeat the rubric phrase.", "Write one coherent topic sentence."],
    rubric: ["stress", "rubric fluency", "meaning"],
    tags: ["writing rubric", "coherence", "pronunciation"],
    localeNotes: {
      en: "Use before writing review so rubric language becomes familiar.",
      fa: "قبل از بازبيني Writing خوب است تا زبان rubric آشنا شود.",
    },
  },
  {
    id: "pronunciation-inference",
    track: "pronunciation",
    exam: "EduPocket",
    skill: "pronunciation",
    title: "inference /ˈɪn.fɚ.əns/",
    level: "B2",
    timeLimitMinutes: 5,
    summary: "Reading-question keyword drill.",
    sourceUse: "Pairs with TOEFL reading and IELTS reading tasks.",
    sourceTypeTargets: ["reading-lab-rc", "chapter-quiz"],
    ttsScript: "inference. Make an inference. The answer is not stated directly, so you need an inference.",
    questions: [],
    routine: ["Listen.", "Repeat the first syllable.", "Say the sentence twice.", "Find one inference question."],
    rubric: ["stress", "reading vocabulary", "shadowing"],
    tags: ["reading", "inference", "TOEFL"],
    localeNotes: {
      en: "Use when the learner confuses direct detail with inference.",
      fa: "براي وقتي كه زبان آموز Detail و Inference را اشتباه مي گيرد.",
    },
  },
  {
    id: "pronunciation-revision",
    track: "pronunciation",
    exam: "EduPocket",
    skill: "pronunciation",
    title: "revision /rɪˈvɪʒ.ən/",
    level: "B1",
    timeLimitMinutes: 5,
    summary: "A compact drill for a central writing-vault action.",
    sourceUse: "Pairs with all draft and feedback pages.",
    sourceTypeTargets: ["journal", "progress"],
    ttsScript: "revision. A serious draft needs revision. Revision turns a weak answer into learning evidence.",
    questions: [],
    routine: ["Listen.", "Repeat the ZH sound.", "Shadow the full sentence.", "Revise one sentence in the vault."],
    rubric: ["sound accuracy", "sentence rhythm", "action transfer"],
    tags: ["revision", "writing vault", "pronunciation"],
    localeNotes: {
      en: "Use when the learner treats first drafts as final answers.",
      fa: "براي وقتي كه زبان آموز پيش نويس اول را جواب نهايي مي داند.",
    },
  },
  {
    id: "pronunciation-ministry",
    track: "pronunciation",
    exam: "EduPocket",
    skill: "pronunciation",
    title: "ministry /ˈmɪn.ə.stri/",
    level: "B1",
    timeLimitMinutes: 5,
    summary: "Context word pronunciation for religious-service content.",
    sourceUse: "Pairs with religious context and service scenarios.",
    sourceTypeTargets: ["scenario", "exegesis", "translation"],
    ttsScript: "ministry. learning ministry. A learning ministry can support language, care, and service.",
    questions: [],
    routine: ["Listen.", "Keep it three syllables.", "Repeat with care and service.", "Use it in one context sentence."],
    rubric: ["syllable control", "context use", "shadowing"],
    tags: ["religious context", "service", "pronunciation"],
    localeNotes: {
      en: "Use in religious context modules without making the page crowded.",
      fa: "براي ماژول هاي Religious Context بدون شلوغ كردن صفحه.",
    },
  },
  {
    id: "pronunciation-thought-though",
    track: "pronunciation",
    exam: "EduPocket",
    skill: "pronunciation",
    title: "thought /θɔːt/ vs though /ðoʊ/",
    level: "B2",
    timeLimitMinutes: 7,
    summary: "Minimal-pair drill for TH sounds and vowel contrast.",
    sourceUse: "Pairs with speaking rehearsal and reading aloud.",
    sourceTypeTargets: ["listening-speaking", "vocabulary"],
    ttsScript: "thought. though. I thought about it, though I was not ready to answer.",
    questions: [],
    routine: ["Listen.", "Touch teeth lightly for TH.", "Separate thought and though.", "Shadow the sentence slowly."],
    rubric: ["TH contrast", "vowel contrast", "sentence rhythm"],
    tags: ["minimal pair", "TH", "pronunciation"],
    localeNotes: {
      en: "Use for a high-impact English sound contrast.",
      fa: "براي يكي از تفاوت هاي مهم صدايي انگليسي.",
    },
  },
  {
    id: "pronunciation-result-resource",
    track: "pronunciation",
    exam: "EduPocket",
    skill: "pronunciation",
    title: "result /rɪˈzʌlt/ vs resource /ˈriː.sɔːrs/",
    level: "B2",
    timeLimitMinutes: 6,
    summary: "Stress contrast for two common academic words.",
    sourceUse: "Pairs with lexical resource and writing rubrics.",
    sourceTypeTargets: ["vocabulary", "progress"],
    ttsScript: "result. resource. A good resource should lead to a visible result.",
    questions: [],
    routine: ["Listen.", "Mark final stress in result.", "Mark first stress in resource.", "Say the sentence twice."],
    rubric: ["stress contrast", "academic vocabulary", "shadowing"],
    tags: ["stress", "lexical resource", "pronunciation"],
    localeNotes: {
      en: "Use with lexical resource work and IELTS vocabulary discussion.",
      fa: "همراه Lexical Resource و واژگان IELTS مفيد است.",
    },
  },
  {
    id: "pronunciation-schedule-shadow",
    track: "pronunciation",
    exam: "EduPocket",
    skill: "pronunciation",
    title: "schedule /ˈskedʒ.uːl/",
    level: "B1",
    timeLimitMinutes: 5,
    summary: "Routine word for weekly/monthly update language.",
    sourceUse: "Pairs with update promises and review engine.",
    sourceTypeTargets: ["progress", "journal"],
    ttsScript: "schedule. review schedule. A clear schedule helps learners return before weak items disappear.",
    questions: [],
    routine: ["Listen.", "Repeat the SK sound.", "Shadow the full sentence.", "Plan one review schedule."],
    rubric: ["initial cluster", "sentence flow", "action transfer"],
    tags: ["review", "schedule", "pronunciation"],
    localeNotes: {
      en: "Use when setting weekly and monthly update expectations.",
      fa: "براي برنامه مرور هفتگي و ماهانه مناسب است.",
    },
  },
  {
    id: "pronunciation-specific-general",
    track: "pronunciation",
    exam: "EduPocket",
    skill: "pronunciation",
    title: "specific /spəˈsɪf.ɪk/ vs general /ˈdʒen.ər.əl/",
    level: "B2",
    timeLimitMinutes: 6,
    summary: "Writing feedback pair for better examples.",
    sourceUse: "Pairs with teacher notes and writing revision.",
    sourceTypeTargets: ["journal", "progress"],
    ttsScript: "specific. general. Your example is too general. Add one specific event and explain the result.",
    questions: [],
    routine: ["Listen.", "Contrast stress.", "Repeat the feedback sentence.", "Revise one general example."],
    rubric: ["stress", "feedback fluency", "revision"],
    tags: ["writing feedback", "specific examples", "pronunciation"],
    localeNotes: {
      en: "Use whenever Ali asks for stronger support in writing.",
      fa: "هر وقت در Writing نياز به مثال مشخص تر باشد.",
    },
  },
  {
    id: "pronunciation-web-peace-patience",
    track: "pronunciation",
    exam: "EduPocket",
    skill: "pronunciation",
    title: "Public-domain shadowing: peace and patience",
    level: "B1",
    timeLimitMinutes: 7,
    summary: "A WEB public-domain shadowing drill for /p/ clarity, phrase rhythm, and calm delivery.",
    sourceUse: "Uses copied public-domain Bible phrases for pronunciation and shadowing practice.",
    sourceTypeTargets: ["listening-speaking", "vocabulary", "scenario"],
    ttsScript: "But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faith, gentleness, and self-control. Against such things there is no law.",
    questions: [],
    routine: ["Listen once.", "Mark the /p/ sound in peace and patience.", "Shadow the list in groups of three.", "Record one mastered phrase in pronunciation notes."],
    rubric: ["phrase grouping", "initial /p/ clarity", "calm intonation"],
    sourceProvenance: [worldEnglishBibleProvenance],
    tags: ["public domain", "WEB", "Galatians 5", "pronunciation", "shadowing", "ministry vocabulary"],
    localeNotes: {
      en: "Use as a calm pronunciation drill that also builds high-frequency religious vocabulary.",
      fa: "برای تمرین تلفظ آرام و واژگان پرکاربرد مذهبی مناسب است.",
    },
  },
];

export const evaTeacherMaterials: EvaMaterialItem[] = [
  {
    id: "teacher-feedback-bank-specificity",
    track: "teacher",
    exam: "EduPocket",
    skill: "teacher-feedback",
    title: "Teacher feedback bank: specificity",
    level: "B2",
    timeLimitMinutes: 8,
    summary: "Reusable feedback language Ali can paste or adapt in Teacher Lens.",
    sourceUse: "Pairs with writing vault and teacher notes.",
    sourceTypeTargets: ["journal", "progress"],
    prompt: "Feedback template: Your idea is clear, but the support is still general. Add one specific event, name who was involved, and explain the result in one sentence.",
    questions: [],
    routine: ["Read the draft.", "Name the missing evidence.", "Paste the template.", "Add one personal line for the learner."],
    rubric: ["specificity", "teacher action", "learner next step"],
    tags: ["teacher lens", "writing feedback", "specificity"],
    localeNotes: {
      en: "For teacher review when a draft has ideas but not enough proof.",
      fa: "براي وقتي كه متن ايده دارد ولي شاهد كافي ندارد.",
    },
  },
  {
    id: "teacher-feedback-bank-grammar",
    track: "teacher",
    exam: "EduPocket",
    skill: "teacher-feedback",
    title: "Teacher feedback bank: grammar pattern",
    level: "B1",
    timeLimitMinutes: 8,
    summary: "A feedback template for repeated grammar errors.",
    sourceUse: "Pairs with grammar modules and weak skill map.",
    sourceTypeTargets: ["grammar-practice", "progress"],
    prompt: "Feedback template: I see the same grammar pattern three times. Do not correct only this sentence. Write the rule, make two new examples, and add this pattern to your review queue.",
    questions: [],
    routine: ["Find the repeated pattern.", "Link the note to a grammar module.", "Ask for two fresh examples."],
    rubric: ["pattern noticing", "rule explanation", "review transfer"],
    tags: ["teacher lens", "grammar", "review queue"],
    localeNotes: {
      en: "For repeated grammar problems that need a reusable rule.",
      fa: "براي خطاهاي گرامري تكراري كه نياز به قانون قابل استفاده دارند.",
    },
  },
  {
    id: "teacher-feedback-bank-pronunciation",
    track: "teacher",
    exam: "EduPocket",
    skill: "teacher-feedback",
    title: "Teacher feedback bank: pronunciation",
    level: "B1",
    timeLimitMinutes: 7,
    summary: "A feedback template for shadowing and TTS follow-up.",
    sourceUse: "Pairs with Pronunciation Lab.",
    sourceTypeTargets: ["listening-speaking", "vocabulary"],
    prompt: "Feedback template: This word is understandable, but the stress is not stable yet. Listen once, repeat twice, then record yourself saying the word inside a full sentence.",
    questions: [],
    routine: ["Choose the word.", "Assign Listen + Repeat + sentence.", "Check the next recording."],
    rubric: ["stress", "repeat count", "sentence transfer"],
    tags: ["pronunciation", "TTS", "teacher feedback"],
    localeNotes: {
      en: "For pronunciation that needs a concrete repeat routine.",
      fa: "براي تلفظي كه بايد به يك روال تكرار دقيق تبديل شود.",
    },
  },
  {
    id: "teacher-feedback-bank-review",
    track: "teacher",
    exam: "EduPocket",
    skill: "teacher-feedback",
    title: "Teacher feedback bank: review queue",
    level: "B2",
    timeLimitMinutes: 7,
    summary: "A feedback template for turning mistakes into review items.",
    sourceUse: "Pairs with Review Engine and Smart Next Step.",
    sourceTypeTargets: ["progress", "chapter-quiz"],
    prompt: "Feedback template: This mistake should not disappear after today. Add it to review with a reason: what confused you, what the correct answer is, and when you will check it again.",
    questions: [],
    routine: ["Name the confusion.", "State the correct answer.", "Schedule review."],
    rubric: ["review reason", "correct answer", "schedule"],
    tags: ["review engine", "teacher lens", "weak skill map"],
    localeNotes: {
      en: "For errors that need deliberate return, not just correction.",
      fa: "براي خطاهايي كه فقط اصلاح نمي خواهند، بلكه برگشت هدفمند لازم دارند.",
    },
  },
  {
    id: "teacher-feedback-bank-thesis",
    track: "teacher",
    exam: "EduPocket",
    skill: "teacher-feedback",
    title: "Teacher feedback bank: thesis control",
    level: "B2",
    timeLimitMinutes: 8,
    summary: "A feedback template for unclear IELTS/TOEFL positions.",
    sourceUse: "Pairs with Writing Studio, Exam Mode, and paragraph control.",
    sourceTypeTargets: ["reading-lab-rc", "progress", "chapter-quiz"],
    prompt: "Feedback template: Your position is present, but it is not sharp enough yet. Rewrite the first sentence so it names the topic, your position, and the reason you will defend.",
    questions: [],
    routine: ["Find the current position.", "Ask whether the reader can predict the paragraph.", "Rewrite the thesis in one sentence.", "Add one reason only."],
    rubric: ["position clarity", "topic control", "reason focus"],
    tags: ["teacher lens", "IELTS writing", "TOEFL writing", "thesis"],
    localeNotes: {
      en: "For writing that has ideas but no controlling sentence.",
      fa: "براي متني كه ايده دارد اما جمله كنترل كننده روشن ندارد.",
    },
  },
  {
    id: "teacher-feedback-bank-cohesion",
    track: "teacher",
    exam: "EduPocket",
    skill: "teacher-feedback",
    title: "Teacher feedback bank: cohesion",
    level: "B2",
    timeLimitMinutes: 8,
    summary: "A feedback template for paragraphs that feel disconnected.",
    sourceUse: "Pairs with connector grammar, Writing Vault, and IELTS cohesion review.",
    sourceTypeTargets: ["grammar-practice", "reading-lab", "progress"],
    prompt: "Feedback template: The sentences are mostly correct, but the paragraph does not move smoothly. Add one connector for contrast or result, then repeat one key noun so the reader can follow the logic.",
    questions: [],
    routine: ["Mark the topic sentence.", "Circle unclear jumps.", "Add one connector.", "Repeat one key noun naturally."],
    rubric: ["cohesion", "reference control", "logical movement"],
    tags: ["cohesion", "connectors", "teacher lens", "IELTS writing"],
    localeNotes: {
      en: "For drafts with correct sentences but weak paragraph flow.",
      fa: "براي متن هايي كه جمله ها درست اند اما جريان پاراگراف ضعيف است.",
    },
  },
  {
    id: "teacher-feedback-bank-lexical-resource",
    track: "teacher",
    exam: "EduPocket",
    skill: "teacher-feedback",
    title: "Teacher feedback bank: lexical resource",
    level: "B2",
    timeLimitMinutes: 7,
    summary: "A feedback template for vocabulary range without overcomplication.",
    sourceUse: "Pairs with Pronunciation Lab, lexical cards, and source-page notes.",
    sourceTypeTargets: ["vocabulary", "chapter-language", "progress"],
    prompt: "Feedback template: Choose one basic word you repeated too often. Replace it with a precise academic or ministry word, then write one collocation and one sentence using it naturally.",
    questions: [],
    routine: ["Find one repeated word.", "Choose a precise replacement.", "Write one collocation.", "Use it in a sentence connected to the page."],
    rubric: ["word choice", "collocation", "natural sentence use"],
    tags: ["lexical resource", "vocabulary", "pronunciation", "teacher lens"],
    localeNotes: {
      en: "For vocabulary growth that should stay natural and usable.",
      fa: "براي رشد واژگان بدون سنگين و غيرطبيعي شدن متن.",
    },
  },
  {
    id: "teacher-feedback-bank-exam-routine",
    track: "teacher",
    exam: "EduPocket",
    skill: "teacher-feedback",
    title: "Teacher feedback bank: exam routine",
    level: "B1",
    timeLimitMinutes: 7,
    summary: "A feedback template for timed practice discipline.",
    sourceUse: "Pairs with Exam Mode timer and review queue.",
    sourceTypeTargets: ["chapter-quiz", "progress", "reading-lab-rc"],
    prompt: "Feedback template: Do this task again with the timer. Spend two minutes previewing, answer without stopping, then use the answer key only after you write one reason for each choice.",
    questions: [],
    routine: ["Set the timer.", "Preview for two minutes.", "Answer without pausing.", "Explain each choice before checking."],
    rubric: ["timing", "answer discipline", "rationale before key"],
    tags: ["exam mode", "timed practice", "review engine", "teacher lens"],
    localeNotes: {
      en: "For learners who know the content but lose discipline under time.",
      fa: "براي زبان آموزي كه محتوا را مي داند اما زير زمان نظم خود را از دست مي دهد.",
    },
  },
  {
    id: "teacher-public-domain-source-assignment",
    track: "teacher",
    exam: "EduPocket",
    skill: "teacher-feedback",
    title: "Teacher assignment: public-domain source pack",
    level: "B2",
    timeLimitMinutes: 9,
    summary: "A Teacher Lens template for assigning WEB-based reading, writing, TTS, and review tasks responsibly.",
    sourceUse: "Pairs with all public-domain WEB material packs and keeps attribution visible in the learner workflow.",
    sourceTypeTargets: ["exegesis", "chapter-reading", "listening-speaking", "progress"],
    prompt:
      "Assignment template: Complete one public-domain source pack. First, read or listen to the source text. Second, answer the questions without outside help. Third, save one writing response. Fourth, add one weak vocabulary or pronunciation item to review. Keep the source attribution visible in your note.",
    questions: [],
    routine: ["Choose one WEB material.", "Check the source provenance card.", "Assign reading or listening first.", "Require one saved draft.", "Review the weak item in Teacher Lens."],
    rubric: ["source awareness", "completed evidence", "review decision", "teacher follow-up"],
    sourceProvenance: [worldEnglishBibleProvenance, edupocketOriginalProvenance],
    tags: ["teacher lens", "public domain", "WEB", "assignment", "source provenance"],
    localeNotes: {
      en: "For Ali's review workflow: the student learns from a legal source, but all assessment and tracking stay inside EduPocket.",
      fa: "برای جریان کار علی: متن منبع قانونی است، اما ارزیابی و tracking داخل EduPocket انجام می‌شود.",
    },
  },
];

export const evaMaterialCollections = [
  {
    id: "reading" as const,
    title: "Reading Packs",
    description: "Original IELTS/TOEFL-style passages with answer keys and rationales.",
    items: evaReadingMaterials,
  },
  {
    id: "writing" as const,
    title: "Writing Studio",
    description: "Task 1, Task 2, academic discussion, and integrated-style prompts.",
    items: evaWritingMaterials,
  },
  {
    id: "listening" as const,
    title: "Listening + TTS",
    description: "Browser-speech scripts for listening, shadowing, and study rituals.",
    items: evaListeningMaterials,
  },
  {
    id: "pronunciation" as const,
    title: "Pronunciation Drills",
    description: "Stress, IPA, minimal pairs, and shadowing checklists.",
    items: evaPronunciationMaterials,
  },
  {
    id: "teacher" as const,
    title: "Teacher Bank",
    description: "Feedback templates and action language for Teacher Lens.",
    items: evaTeacherMaterials,
  },
];

export const evaMaterialItems: EvaMaterialItem[] = evaMaterialCollections.flatMap((collection) => collection.items);

export const evaMaterialStats = {
  collections: evaMaterialCollections.length,
  items: evaMaterialItems.length,
  readingQuestions: evaReadingMaterials.reduce((total, item) => total + item.questions.length, 0),
  listeningQuestions: evaListeningMaterials.reduce((total, item) => total + item.questions.length, 0),
  ttsScripts: evaMaterialItems.filter((item) => item.ttsScript || item.passage).length,
  writingPrompts: evaWritingMaterials.length,
  pronunciationDrills: evaPronunciationMaterials.length,
  teacherTemplates: evaTeacherMaterials.length,
};

export const evaSupplementalExamTasks = [...evaReadingMaterials, ...evaWritingMaterials].map((material) => ({
  id: `material-exam-${material.id}`,
  exam: material.exam === "TOEFL" ? "TOEFL" : "IELTS",
  skill: material.skill === "writing" ? "writing" : "reading",
  title: material.title,
  level: material.level,
  timeLimitMinutes: material.timeLimitMinutes,
  passage: material.passage,
  prompt: material.prompt ?? material.summary,
  rubric: material.rubric,
  questions: material.questions,
}));
