function productionUrl() {
  const explicitUrl = process.env.NEXT_PUBLIC_SITE_URL;
  const vercelProductionUrl = process.env.VERCEL_PROJECT_PRODUCTION_URL;
  const vercelUrl = process.env.VERCEL_URL;
  const url = (explicitUrl ?? vercelProductionUrl ?? vercelUrl)?.trim();

  if (!url) return "https://edupocket.org";
  return (url.startsWith("http") ? url : `https://${url}`).replace(/\/$/, "");
}

export const siteConfig = {
  name: "EduPocket",
  tagline: "Practical English coaching, exam preparation, specialized English, AI learning systems, and education technology.",
  faTagline: "کوچینگ کاربردی انگلیسی، آمادگی آزمون، زبان تخصصی، سیستم‌های یادگیری با AI و تکنولوژی آموزشی.",
  description:
    "EduPocket is Ali Rad's learning hub for practical English coaching, IELTS, TOEFL, Cambridge English, GRE, GMAT, specialized English, AI-assisted study systems, teaching frameworks, and audio lessons.",
  faDescription:
    "EduPocket هاب یادگیری علی راد برای کوچینگ کاربردی انگلیسی، آیلتس، تافل، آزمون‌های کمبریج، GRE، GMAT، زبان تخصصی، سیستم‌های مطالعه با AI، چارچوب‌های تدریس و درس‌های صوتی است.",
  author: "Ali Esfandiari Rad",
  shortAuthor: "Ali Rad",
  url: productionUrl(),
  canonicalUrl: "https://edupocket.org",
  contactEmail: "aliesfandiari@outlook.com",
  contact: {
    telegram: {
      label: "Telegram",
      faLabel: "تلگرام",
      handle: "@esfandiari_Rad",
      href: "https://t.me/esfandiari_Rad",
    },
    instagram: {
      label: "insta",
      faLabel: "insta",
      handle: "@esfandiari_RAD",
      href: "https://www.instagram.com/esfandiari_RAD/",
    },
    bale: {
      label: "Bale",
      faLabel: "بله",
      handle: "@esfandiari_1991",
      href: "https://ble.ir/esfandiari_1991",
    },
    email: {
      label: "Email",
      faLabel: "ایمیل",
      handle: "aliesfandiari@outlook.com",
      href: "mailto:aliesfandiari@outlook.com?subject=EduPocket%20Direct%20Message",
    },
  },
  topics: [
    "AI Learning",
    "English Teaching",
    "Online English Tutoring",
    "IELTS, TOEFL & English Exams",
    "Cambridge English",
    "FCE / B2 First",
    "CAE / C1 Advanced",
    "GRE Verbal",
    "GMAT Verbal",
    "KET",
    "PET",
    "PTE Academic",
    "Duolingo English Test",
    "OET",
    "LanguageCert",
    "TOEIC",
    "CELPIP",
    "CAEL",
    "Business English",
    "Academic Writing",
    "English for Kids and Teens",
    "English for Specific Purposes",
    "Specialized English",
    "Medical English",
    "Engineering English",
    "Technology English",
    "Business and Finance English",
    "Legal English",
    "Academic and Research English",
    "Study Systems",
    "Programming",
    "SQL",
    "Python",
    "Arabic & Languages",
    "Teaching Frameworks",
    "Mini Apps",
    "Book Summaries",
    "Podcasts",
  ],
  seoKeywords: [
    "EduPocket",
    "Ali Esfandiari Rad",
    "Ali Rad",
    "Ali Rad English teacher",
    "Cambridge CELTA-qualified English teacher",
    "CELTA-qualified English tutor",
    "CELTA-certified English tutor",
    "English coaching",
    "English teacher with 15 years experience",
    "AI learning systems",
    "Persian English learning",
    "Chinese English learning",
    "English test practice",
    "online English tutor",
    "online English teacher for Taiwan students",
    "online English teacher for China students",
    "English tutor United States",
    "English tutor Canada",
    "AI-assisted English learning",
    "IELTS TOEFL lessons",
    "IELTS tutor online",
    "TOEFL iBT tutor",
    "PTE Academic tutor",
    "Duolingo English Test tutor",
    "TOEIC tutor",
    "OET English tutor",
    "LanguageCert tutor",
    "CELPIP tutor",
    "CAEL tutor",
    "FCE teacher for teens",
    "Cambridge B2 First teacher",
    "GRE verbal tutor",
    "GMAT verbal tutor",
    "specialized English teacher",
    "English for Specific Purposes tutor",
    "ESP English tutor",
    "medical English tutor",
    "engineering English tutor",
    "business English tutor",
    "finance English tutor",
    "legal English tutor",
    "technology English tutor",
    "academic research English tutor",
    "English for doctors",
    "English for engineers",
    "English for programmers",
    "English for nurses",
    "English for lawyers",
    "English for managers",
    "English for presentations",
    "مدرس زبان تخصصی",
    "زبان تخصصی پزشکی",
    "زبان تخصصی مهندسی",
    "زبان تخصصی کامپیوتر",
    "زبان تخصصی مدیریت",
    "زبان تخصصی حقوق",
    "study systems",
    "micro lessons",
    "education technology",
    "language learning",
    "Blue Rose Academy",
    "Eva Digital Booklet",
    "digital English booklet",
  ],
  teacherProfile: {
    yearsOfExperience: "15+",
    credential: "Cambridge CELTA-qualified English teacher",
    credentialFa: "دارنده مدرک CELTA کمبریج",
    role: "Online English teacher, exam-preparation coach, and AI learning-system designer",
    faRole: "مدرس آنلاین انگلیسی، کوچ آمادگی آزمون و طراح سیستم یادگیری با AI",
    examPrep: [
      "IELTS Academic",
      "IELTS General Training",
      "TOEFL iBT",
      "TOEFL Essentials",
      "TOEFL ITP",
      "Cambridge FCE / B2 First",
      "Cambridge CAE / C1 Advanced",
      "Cambridge CPE / C2 Proficiency",
      "Cambridge KET / A2 Key",
      "Cambridge PET / B1 Preliminary",
      "Cambridge YLE / Pre A1 Starters",
      "Cambridge YLE / A1 Movers",
      "Cambridge YLE / A2 Flyers",
      "Cambridge Linguaskill",
      "PTE Academic",
      "PTE Core",
      "Duolingo English Test",
      "TOEIC",
      "OET",
      "LanguageCert International ESOL",
      "Oxford Test of English",
      "Michigan MET",
      "Michigan ECCE",
      "Michigan ECPE",
      "iTEP",
      "CELPIP",
      "CAEL",
      "MSRT",
      "TOLIMO",
      "EPT",
      "UTEPT",
      "MHLE",
      "GRE Verbal",
      "GMAT Verbal",
      "SAT English",
      "ACT English",
      "AP English Language",
      "AP English Literature",
      "Business English",
      "Academic Writing",
      "English for kids and teens",
    ],
    globalLanguageExams: [
      "DELF",
      "DALF",
      "TCF",
      "TEF",
      "Goethe-Zertifikat",
      "TestDaF",
      "DSH",
      "telc Deutsch",
      "DELE",
      "SIELE",
      "HSK",
      "HSKK",
      "YCT",
      "JLPT",
      "J-Test",
      "NAT-TEST",
      "TOPIK",
      "TOMER",
      "ALPT",
    ],
    specializedEnglish: [
      "Medical English",
      "Nursing and healthcare English",
      "Engineering English",
      "Computer Science and Programming English",
      "AI and Data Science English",
      "Business and Management English",
      "Finance and Accounting English",
      "Legal English",
      "Tourism and Hospitality English",
      "Aviation English",
      "Academic and Research English",
      "Presentation and Interview English",
    ],
    faExamPrep: [
      "IELTS Academic",
      "IELTS General Training",
      "TOEFL iBT",
      "TOEFL Essentials",
      "TOEFL ITP",
      "Cambridge FCE / B2 First",
      "Cambridge CAE / C1 Advanced",
      "Cambridge CPE / C2 Proficiency",
      "Cambridge KET / A2 Key",
      "Cambridge PET / B1 Preliminary",
      "Cambridge YLE / Pre A1 Starters",
      "Cambridge YLE / A1 Movers",
      "Cambridge YLE / A2 Flyers",
      "Cambridge Linguaskill",
      "PTE Academic",
      "PTE Core",
      "Duolingo English Test",
      "TOEIC",
      "OET",
      "LanguageCert International ESOL",
      "Oxford Test of English",
      "Michigan MET",
      "Michigan ECCE",
      "Michigan ECPE",
      "iTEP",
      "CELPIP",
      "CAEL",
      "MSRT",
      "TOLIMO",
      "EPT",
      "UTEPT",
      "MHLE",
      "GRE Verbal",
      "GMAT Verbal",
      "SAT English",
      "ACT English",
      "AP English Language",
      "AP English Literature",
      "Business English",
      "Academic Writing",
      "انگلیسی کودکان و نوجوانان",
    ],
    faSpecializedEnglish: [
      "زبان تخصصی پزشکی",
      "زبان تخصصی پرستاری و سلامت",
      "زبان تخصصی مهندسی",
      "زبان تخصصی کامپیوتر و برنامه‌نویسی",
      "زبان تخصصی هوش مصنوعی و دیتا ساینس",
      "زبان تخصصی مدیریت و کسب‌وکار",
      "زبان تخصصی مالی و حسابداری",
      "زبان تخصصی حقوق",
      "زبان تخصصی گردشگری و هتلداری",
      "زبان تخصصی هواپیمایی",
      "زبان تخصصی پژوهش و دانشگاه",
      "زبان ارائه و مصاحبه",
    ],
    regions: ["Iran", "China", "Taiwan", "United States", "Canada", "Europe", "Online worldwide"],
    faRegions: ["ایران", "چین", "تایوان", "آمریکا", "کانادا", "اروپا", "آنلاین در سراسر جهان"],
  },
  nav: [
    { href: "/", label: "Home", faLabel: "خانه" },
    { href: "/articles", label: "Articles", faLabel: "مقاله‌ها" },
    { href: "/lessons", label: "Lessons", faLabel: "درس‌ها" },
    { href: "/english-lab", label: "English Lab", faLabel: "آزمایشگاه زبان" },
    { href: "/podcasts", label: "Podcasts", faLabel: "پادکست‌ها" },
    { href: "/about", label: "About", faLabel: "درباره" },
  ],
} as const;

export type SiteTopic = (typeof siteConfig.topics)[number];
