function productionUrl() {
  const explicitUrl = process.env.NEXT_PUBLIC_SITE_URL;
  const vercelProductionUrl = process.env.VERCEL_PROJECT_PRODUCTION_URL;
  const vercelUrl = process.env.VERCEL_URL;
  const url = (explicitUrl ?? vercelProductionUrl ?? vercelUrl)?.trim();

  if (!url) return "https://edupocket.org";
  return (url.startsWith("http") ? url : `https://${url}`).replace(/\/$/, "");
}

export const siteConfig = {
  name: "EduPocket",
  tagline: "Practical English coaching, exam preparation, AI learning systems, and education technology.",
  faTagline: "کوچینگ کاربردی انگلیسی، آمادگی آزمون، سیستم‌های یادگیری با AI و تکنولوژی آموزشی.",
  description:
    "EduPocket is Ali Rad's learning hub for practical English coaching, IELTS, TOEFL, Cambridge English, GRE, GMAT, AI-assisted study systems, teaching frameworks, and audio lessons.",
  faDescription:
    "EduPocket هاب یادگیری علی راد برای کوچینگ کاربردی انگلیسی، آیلتس، تافل، آزمون‌های کمبریج، GRE، GMAT، سیستم‌های مطالعه با AI، چارچوب‌های تدریس و درس‌های صوتی است.",
  author: "Ali Esfandiari Rad",
  shortAuthor: "Ali Rad",
  url: productionUrl(),
  canonicalUrl: "https://edupocket.org",
  contactEmail: "aliesfandiari@outlook.com",
  contact: {
    telegram: {
      label: "Telegram",
      faLabel: "تلگرام",
      handle: "@esfandiari_Rad",
      href: "https://t.me/esfandiari_Rad",
    },
    instagram: {
      label: "insta",
      faLabel: "insta",
      handle: "@esfandiari_RAD",
      href: "https://www.instagram.com/esfandiari_RAD/",
    },
    bale: {
      label: "Bale",
      faLabel: "بله",
      handle: "@esfandiari_1991",
      href: "https://ble.ir/esfandiari_1991",
    },
    email: {
      label: "Email",
      faLabel: "ایمیل",
      handle: "aliesfandiari@outlook.com",
      href: "mailto:aliesfandiari@outlook.com?subject=EduPocket%20Direct%20Message",
    },
  },
  topics: [
    "AI Learning",
    "English Teaching",
    "Online English Tutoring",
    "IELTS & TOEFL",
    "Cambridge English",
    "FCE / B2 First",
    "CAE / C1 Advanced",
    "GRE Verbal",
    "GMAT Verbal",
    "KET",
    "PET",
    "PTE Academic",
    "Duolingo English Test",
    "Business English",
    "Academic Writing",
    "English for Kids and Teens",
    "Study Systems",
    "Programming",
    "SQL",
    "Python",
    "Arabic & Languages",
    "Teaching Frameworks",
    "Mini Apps",
    "Book Summaries",
    "Podcasts",
  ],
  seoKeywords: [
    "EduPocket",
    "Ali Esfandiari Rad",
    "Ali Rad",
    "Ali Rad English teacher",
    "Cambridge CELTA English teacher",
    "CELTA holder English tutor",
    "English coaching",
    "English teacher with 15 years experience",
    "AI learning systems",
    "Persian English learning",
    "Chinese English learning",
    "English test practice",
    "online English tutor",
    "online English teacher for Taiwan students",
    "online English teacher for China students",
    "English tutor United States",
    "English tutor Canada",
    "AI-assisted English learning",
    "IELTS TOEFL lessons",
    "IELTS tutor online",
    "TOEFL iBT tutor",
    "FCE teacher for teens",
    "Cambridge B2 First teacher",
    "GRE verbal tutor",
    "GMAT verbal tutor",
    "study systems",
    "micro lessons",
    "education technology",
    "language learning",
    "Blue Rose Academy",
    "Eva Digital Booklet",
    "digital English booklet",
  ],
  teacherProfile: {
    yearsOfExperience: "15+",
    credential: "Cambridge CELTA holder",
    credentialFa: "دارنده CELTA کمبریج",
    role: "Online English teacher, exam-preparation coach, and AI learning-system designer",
    faRole: "مدرس آنلاین انگلیسی، کوچ آمادگی آزمون و طراح سیستم یادگیری با AI",
    examPrep: [
      "IELTS Academic",
      "IELTS General Training",
      "TOEFL iBT",
      "Cambridge FCE / B2 First",
      "Cambridge CAE / C1 Advanced",
      "Cambridge CPE / C2 Proficiency",
      "Cambridge KET / A2 Key",
      "Cambridge PET / B1 Preliminary",
      "PTE Academic",
      "Duolingo English Test",
      "TOEIC",
      "GRE Verbal",
      "GMAT Verbal",
      "SAT English",
      "ACT English",
      "Business English",
      "Academic Writing",
      "English for kids and teens",
    ],
    faExamPrep: [
      "IELTS Academic",
      "IELTS General Training",
      "TOEFL iBT",
      "Cambridge FCE / B2 First",
      "Cambridge CAE / C1 Advanced",
      "Cambridge CPE / C2 Proficiency",
      "Cambridge KET / A2 Key",
      "Cambridge PET / B1 Preliminary",
      "PTE Academic",
      "Duolingo English Test",
      "TOEIC",
      "GRE Verbal",
      "GMAT Verbal",
      "SAT English",
      "ACT English",
      "Business English",
      "Academic Writing",
      "انگلیسی کودکان و نوجوانان",
    ],
    regions: ["Iran", "China", "Taiwan", "United States", "Canada", "Europe", "Online worldwide"],
    faRegions: ["ایران", "چین", "تایوان", "آمریکا", "کانادا", "اروپا", "آنلاین در سراسر جهان"],
  },
  nav: [
    { href: "/", label: "Home", faLabel: "خانه" },
    { href: "/articles", label: "Articles", faLabel: "مقاله‌ها" },
    { href: "/lessons", label: "Lessons", faLabel: "درس‌ها" },
    { href: "/english-lab", label: "English Lab", faLabel: "آزمایشگاه زبان" },
    { href: "/podcasts", label: "Podcasts", faLabel: "پادکست‌ها" },
    { href: "/about", label: "About", faLabel: "درباره" },
  ],
} as const;

export type SiteTopic = (typeof siteConfig.topics)[number];
